// Code generated by ent, DO NOT EDIT.

package usertotp

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wenpiner/last-admin-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldUpdatedAt, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldState, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldUserID, v))
}

// SecretKey applies equality check predicate on the "secret_key" field. It's identical to SecretKeyEQ.
func SecretKey(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldSecretKey, v))
}

// BackupCodes applies equality check predicate on the "backup_codes" field. It's identical to BackupCodesEQ.
func BackupCodes(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldBackupCodes, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldIsEnabled, v))
}

// IsVerified applies equality check predicate on the "is_verified" field. It's identical to IsVerifiedEQ.
func IsVerified(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldIsVerified, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedCode applies equality check predicate on the "last_used_code" field. It's identical to LastUsedCodeEQ.
func LastUsedCode(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldLastUsedCode, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldDeviceName, v))
}

// Issuer applies equality check predicate on the "issuer" field. It's identical to IssuerEQ.
func Issuer(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldIssuer, v))
}

// FailureCount applies equality check predicate on the "failure_count" field. It's identical to FailureCountEQ.
func FailureCount(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldFailureCount, v))
}

// LockedUntil applies equality check predicate on the "locked_until" field. It's identical to LockedUntilEQ.
func LockedUntil(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldLockedUntil, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldUpdatedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldState))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldUserID, vs...))
}

// SecretKeyEQ applies the EQ predicate on the "secret_key" field.
func SecretKeyEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldSecretKey, v))
}

// SecretKeyNEQ applies the NEQ predicate on the "secret_key" field.
func SecretKeyNEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldSecretKey, v))
}

// SecretKeyIn applies the In predicate on the "secret_key" field.
func SecretKeyIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldSecretKey, vs...))
}

// SecretKeyNotIn applies the NotIn predicate on the "secret_key" field.
func SecretKeyNotIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldSecretKey, vs...))
}

// SecretKeyGT applies the GT predicate on the "secret_key" field.
func SecretKeyGT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldSecretKey, v))
}

// SecretKeyGTE applies the GTE predicate on the "secret_key" field.
func SecretKeyGTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldSecretKey, v))
}

// SecretKeyLT applies the LT predicate on the "secret_key" field.
func SecretKeyLT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldSecretKey, v))
}

// SecretKeyLTE applies the LTE predicate on the "secret_key" field.
func SecretKeyLTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldSecretKey, v))
}

// SecretKeyContains applies the Contains predicate on the "secret_key" field.
func SecretKeyContains(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContains(FieldSecretKey, v))
}

// SecretKeyHasPrefix applies the HasPrefix predicate on the "secret_key" field.
func SecretKeyHasPrefix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasPrefix(FieldSecretKey, v))
}

// SecretKeyHasSuffix applies the HasSuffix predicate on the "secret_key" field.
func SecretKeyHasSuffix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasSuffix(FieldSecretKey, v))
}

// SecretKeyEqualFold applies the EqualFold predicate on the "secret_key" field.
func SecretKeyEqualFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEqualFold(FieldSecretKey, v))
}

// SecretKeyContainsFold applies the ContainsFold predicate on the "secret_key" field.
func SecretKeyContainsFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContainsFold(FieldSecretKey, v))
}

// BackupCodesEQ applies the EQ predicate on the "backup_codes" field.
func BackupCodesEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldBackupCodes, v))
}

// BackupCodesNEQ applies the NEQ predicate on the "backup_codes" field.
func BackupCodesNEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldBackupCodes, v))
}

// BackupCodesIn applies the In predicate on the "backup_codes" field.
func BackupCodesIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldBackupCodes, vs...))
}

// BackupCodesNotIn applies the NotIn predicate on the "backup_codes" field.
func BackupCodesNotIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldBackupCodes, vs...))
}

// BackupCodesGT applies the GT predicate on the "backup_codes" field.
func BackupCodesGT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldBackupCodes, v))
}

// BackupCodesGTE applies the GTE predicate on the "backup_codes" field.
func BackupCodesGTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldBackupCodes, v))
}

// BackupCodesLT applies the LT predicate on the "backup_codes" field.
func BackupCodesLT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldBackupCodes, v))
}

// BackupCodesLTE applies the LTE predicate on the "backup_codes" field.
func BackupCodesLTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldBackupCodes, v))
}

// BackupCodesContains applies the Contains predicate on the "backup_codes" field.
func BackupCodesContains(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContains(FieldBackupCodes, v))
}

// BackupCodesHasPrefix applies the HasPrefix predicate on the "backup_codes" field.
func BackupCodesHasPrefix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasPrefix(FieldBackupCodes, v))
}

// BackupCodesHasSuffix applies the HasSuffix predicate on the "backup_codes" field.
func BackupCodesHasSuffix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasSuffix(FieldBackupCodes, v))
}

// BackupCodesIsNil applies the IsNil predicate on the "backup_codes" field.
func BackupCodesIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldBackupCodes))
}

// BackupCodesNotNil applies the NotNil predicate on the "backup_codes" field.
func BackupCodesNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldBackupCodes))
}

// BackupCodesEqualFold applies the EqualFold predicate on the "backup_codes" field.
func BackupCodesEqualFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEqualFold(FieldBackupCodes, v))
}

// BackupCodesContainsFold applies the ContainsFold predicate on the "backup_codes" field.
func BackupCodesContainsFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContainsFold(FieldBackupCodes, v))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsVerifiedEQ applies the EQ predicate on the "is_verified" field.
func IsVerifiedEQ(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldIsVerified, v))
}

// IsVerifiedNEQ applies the NEQ predicate on the "is_verified" field.
func IsVerifiedNEQ(v bool) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldIsVerified, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldLastUsedAt))
}

// LastUsedCodeEQ applies the EQ predicate on the "last_used_code" field.
func LastUsedCodeEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldLastUsedCode, v))
}

// LastUsedCodeNEQ applies the NEQ predicate on the "last_used_code" field.
func LastUsedCodeNEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldLastUsedCode, v))
}

// LastUsedCodeIn applies the In predicate on the "last_used_code" field.
func LastUsedCodeIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldLastUsedCode, vs...))
}

// LastUsedCodeNotIn applies the NotIn predicate on the "last_used_code" field.
func LastUsedCodeNotIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldLastUsedCode, vs...))
}

// LastUsedCodeGT applies the GT predicate on the "last_used_code" field.
func LastUsedCodeGT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldLastUsedCode, v))
}

// LastUsedCodeGTE applies the GTE predicate on the "last_used_code" field.
func LastUsedCodeGTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldLastUsedCode, v))
}

// LastUsedCodeLT applies the LT predicate on the "last_used_code" field.
func LastUsedCodeLT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldLastUsedCode, v))
}

// LastUsedCodeLTE applies the LTE predicate on the "last_used_code" field.
func LastUsedCodeLTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldLastUsedCode, v))
}

// LastUsedCodeContains applies the Contains predicate on the "last_used_code" field.
func LastUsedCodeContains(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContains(FieldLastUsedCode, v))
}

// LastUsedCodeHasPrefix applies the HasPrefix predicate on the "last_used_code" field.
func LastUsedCodeHasPrefix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasPrefix(FieldLastUsedCode, v))
}

// LastUsedCodeHasSuffix applies the HasSuffix predicate on the "last_used_code" field.
func LastUsedCodeHasSuffix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasSuffix(FieldLastUsedCode, v))
}

// LastUsedCodeIsNil applies the IsNil predicate on the "last_used_code" field.
func LastUsedCodeIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldLastUsedCode))
}

// LastUsedCodeNotNil applies the NotNil predicate on the "last_used_code" field.
func LastUsedCodeNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldLastUsedCode))
}

// LastUsedCodeEqualFold applies the EqualFold predicate on the "last_used_code" field.
func LastUsedCodeEqualFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEqualFold(FieldLastUsedCode, v))
}

// LastUsedCodeContainsFold applies the ContainsFold predicate on the "last_used_code" field.
func LastUsedCodeContainsFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContainsFold(FieldLastUsedCode, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameIsNil applies the IsNil predicate on the "device_name" field.
func DeviceNameIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldDeviceName))
}

// DeviceNameNotNil applies the NotNil predicate on the "device_name" field.
func DeviceNameNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldDeviceName))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContainsFold(FieldDeviceName, v))
}

// IssuerEQ applies the EQ predicate on the "issuer" field.
func IssuerEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldIssuer, v))
}

// IssuerNEQ applies the NEQ predicate on the "issuer" field.
func IssuerNEQ(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldIssuer, v))
}

// IssuerIn applies the In predicate on the "issuer" field.
func IssuerIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldIssuer, vs...))
}

// IssuerNotIn applies the NotIn predicate on the "issuer" field.
func IssuerNotIn(vs ...string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldIssuer, vs...))
}

// IssuerGT applies the GT predicate on the "issuer" field.
func IssuerGT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldIssuer, v))
}

// IssuerGTE applies the GTE predicate on the "issuer" field.
func IssuerGTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldIssuer, v))
}

// IssuerLT applies the LT predicate on the "issuer" field.
func IssuerLT(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldIssuer, v))
}

// IssuerLTE applies the LTE predicate on the "issuer" field.
func IssuerLTE(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldIssuer, v))
}

// IssuerContains applies the Contains predicate on the "issuer" field.
func IssuerContains(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContains(FieldIssuer, v))
}

// IssuerHasPrefix applies the HasPrefix predicate on the "issuer" field.
func IssuerHasPrefix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasPrefix(FieldIssuer, v))
}

// IssuerHasSuffix applies the HasSuffix predicate on the "issuer" field.
func IssuerHasSuffix(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldHasSuffix(FieldIssuer, v))
}

// IssuerIsNil applies the IsNil predicate on the "issuer" field.
func IssuerIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldIssuer))
}

// IssuerNotNil applies the NotNil predicate on the "issuer" field.
func IssuerNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldIssuer))
}

// IssuerEqualFold applies the EqualFold predicate on the "issuer" field.
func IssuerEqualFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEqualFold(FieldIssuer, v))
}

// IssuerContainsFold applies the ContainsFold predicate on the "issuer" field.
func IssuerContainsFold(v string) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldContainsFold(FieldIssuer, v))
}

// FailureCountEQ applies the EQ predicate on the "failure_count" field.
func FailureCountEQ(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldFailureCount, v))
}

// FailureCountNEQ applies the NEQ predicate on the "failure_count" field.
func FailureCountNEQ(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldFailureCount, v))
}

// FailureCountIn applies the In predicate on the "failure_count" field.
func FailureCountIn(vs ...int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldFailureCount, vs...))
}

// FailureCountNotIn applies the NotIn predicate on the "failure_count" field.
func FailureCountNotIn(vs ...int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldFailureCount, vs...))
}

// FailureCountGT applies the GT predicate on the "failure_count" field.
func FailureCountGT(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldFailureCount, v))
}

// FailureCountGTE applies the GTE predicate on the "failure_count" field.
func FailureCountGTE(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldFailureCount, v))
}

// FailureCountLT applies the LT predicate on the "failure_count" field.
func FailureCountLT(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldFailureCount, v))
}

// FailureCountLTE applies the LTE predicate on the "failure_count" field.
func FailureCountLTE(v int) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldFailureCount, v))
}

// LockedUntilEQ applies the EQ predicate on the "locked_until" field.
func LockedUntilEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldEQ(FieldLockedUntil, v))
}

// LockedUntilNEQ applies the NEQ predicate on the "locked_until" field.
func LockedUntilNEQ(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNEQ(FieldLockedUntil, v))
}

// LockedUntilIn applies the In predicate on the "locked_until" field.
func LockedUntilIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIn(FieldLockedUntil, vs...))
}

// LockedUntilNotIn applies the NotIn predicate on the "locked_until" field.
func LockedUntilNotIn(vs ...time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotIn(FieldLockedUntil, vs...))
}

// LockedUntilGT applies the GT predicate on the "locked_until" field.
func LockedUntilGT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGT(FieldLockedUntil, v))
}

// LockedUntilGTE applies the GTE predicate on the "locked_until" field.
func LockedUntilGTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldGTE(FieldLockedUntil, v))
}

// LockedUntilLT applies the LT predicate on the "locked_until" field.
func LockedUntilLT(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLT(FieldLockedUntil, v))
}

// LockedUntilLTE applies the LTE predicate on the "locked_until" field.
func LockedUntilLTE(v time.Time) predicate.UserTotp {
	return predicate.UserTotp(sql.FieldLTE(FieldLockedUntil, v))
}

// LockedUntilIsNil applies the IsNil predicate on the "locked_until" field.
func LockedUntilIsNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldIsNull(FieldLockedUntil))
}

// LockedUntilNotNil applies the NotNil predicate on the "locked_until" field.
func LockedUntilNotNil() predicate.UserTotp {
	return predicate.UserTotp(sql.FieldNotNull(FieldLockedUntil))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserTotp {
	return predicate.UserTotp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserTotp {
	return predicate.UserTotp(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTotp) predicate.UserTotp {
	return predicate.UserTotp(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTotp) predicate.UserTotp {
	return predicate.UserTotp(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTotp) predicate.UserTotp {
	return predicate.UserTotp(sql.NotPredicates(p))
}
