// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: core.proto

package server

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/internal/logic/roleservice"
	"github.com/wenpiner/last-admin-core/rpc/internal/svc"
	"github.com/wenpiner/last-admin-core/rpc/types/core"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建或更新角色
func (s *RoleServiceServer) CreateOrUpdateRole(ctx context.Context, in *core.RoleInfo) (*core.RoleInfo, error) {
	l := roleservicelogic.NewCreateOrUpdateRoleLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateRole(in)
}

// 删除角色
func (s *RoleServiceServer) DeleteRole(ctx context.Context, in *core.ID32Request) (*core.BaseResponse, error) {
	l := roleservicelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

// 获取角色
func (s *RoleServiceServer) GetRole(ctx context.Context, in *core.ID32Request) (*core.RoleInfo, error) {
	l := roleservicelogic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

// 获取角色列表
func (s *RoleServiceServer) ListRole(ctx context.Context, in *core.RoleListRequest) (*core.RoleListResponse, error) {
	l := roleservicelogic.NewListRoleLogic(ctx, s.svcCtx)
	return l.ListRole(in)
}

// 通过值获取角色
func (s *RoleServiceServer) GetRoleByValue(ctx context.Context, in *core.StringRequest) (*core.RoleInfo, error) {
	l := roleservicelogic.NewGetRoleByValueLogic(ctx, s.svcCtx)
	return l.GetRoleByValue(in)
}

// 为角色分配菜单
func (s *RoleServiceServer) AssignMenu(ctx context.Context, in *core.RoleMenuRequest) (*core.BaseResponse, error) {
	l := roleservicelogic.NewAssignMenuLogic(ctx, s.svcCtx)
	return l.AssignMenu(in)
}

// 为角色分配API
func (s *RoleServiceServer) AssignApi(ctx context.Context, in *core.RoleApiRequest) (*core.BaseResponse, error) {
	l := roleservicelogic.NewAssignApiLogic(ctx, s.svcCtx)
	return l.AssignApi(in)
}

// 获取角色菜单
func (s *RoleServiceServer) GetMenu(ctx context.Context, in *core.ID32Request) (*core.RoleMenuListResponse, error) {
	l := roleservicelogic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}

// 为角色分配配置项分组权限
func (s *RoleServiceServer) AssignConfigurationGroup(ctx context.Context, in *core.RoleConfigurationGroupRequest) (*core.RoleConfigurationGroupListResponse, error) {
	l := roleservicelogic.NewAssignConfigurationGroupLogic(ctx, s.svcCtx)
	return l.AssignConfigurationGroup(in)
}

// 获取角色配置项分组权限
func (s *RoleServiceServer) GetConfigurationGroup(ctx context.Context, in *core.StringRequest) (*core.RoleConfigurationGroupListResponse, error) {
	l := roleservicelogic.NewGetConfigurationGroupLogic(ctx, s.svcCtx)
	return l.GetConfigurationGroup(in)
}
