// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: core.proto

package tokenservice

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/types/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApiInfo                    = core.ApiInfo
	ApiListRequest             = core.ApiListRequest
	ApiListResponse            = core.ApiListResponse
	BackupCodesResponse        = core.BackupCodesResponse
	BasePageRequest            = core.BasePageRequest
	BasePageResp               = core.BasePageResp
	BaseResponse               = core.BaseResponse
	CleanExpiredTokensRequest  = core.CleanExpiredTokensRequest
	CleanExpiredTokensResponse = core.CleanExpiredTokensResponse
	CreateTokenRequest         = core.CreateTokenRequest
	DepartmentInfo             = core.DepartmentInfo
	DepartmentListRequest      = core.DepartmentListRequest
	DepartmentListResponse     = core.DepartmentListResponse
	DictInfo                   = core.DictInfo
	DictItemInfo               = core.DictItemInfo
	DictItemListRequest        = core.DictItemListRequest
	DictItemListResponse       = core.DictItemListResponse
	DictListRequest            = core.DictListRequest
	DictListResponse           = core.DictListResponse
	DisableTotpRequest         = core.DisableTotpRequest
	EmptyRequest               = core.EmptyRequest
	EnableTotpRequest          = core.EnableTotpRequest
	ID32Request                = core.ID32Request
	ID32SRequest               = core.ID32SRequest
	IDRequest                  = core.IDRequest
	IDSRequest                 = core.IDSRequest
	MenuInfo                   = core.MenuInfo
	MenuListRequest            = core.MenuListRequest
	MenuListResponse           = core.MenuListResponse
	MenuMeta                   = core.MenuMeta
	OauthCallbackRequest       = core.OauthCallbackRequest
	OauthLoginRequest          = core.OauthLoginRequest
	OauthProviderInfo          = core.OauthProviderInfo
	OauthProviderListRequest   = core.OauthProviderListRequest
	OauthProviderListResponse  = core.OauthProviderListResponse
	OauthRedirectResponse      = core.OauthRedirectResponse
	PositionInfo               = core.PositionInfo
	PositionListRequest        = core.PositionListRequest
	PositionListResponse       = core.PositionListResponse
	RoleApiListResponse        = core.RoleApiListResponse
	RoleApiRequest             = core.RoleApiRequest
	RoleInfo                   = core.RoleInfo
	RoleListRequest            = core.RoleListRequest
	RoleListResponse           = core.RoleListResponse
	RoleMenuListResponse       = core.RoleMenuListResponse
	RoleMenuRequest            = core.RoleMenuRequest
	StringListResponse         = core.StringListResponse
	StringRequest              = core.StringRequest
	TokenInfo                  = core.TokenInfo
	TokenListRequest           = core.TokenListRequest
	TokenListResponse          = core.TokenListResponse
	TotpInfo                   = core.TotpInfo
	TotpSetupConfirmResponse   = core.TotpSetupConfirmResponse
	TotpSetupResponse          = core.TotpSetupResponse
	TotpStatusResponse         = core.TotpStatusResponse
	UUIDRequest                = core.UUIDRequest
	UUIDSRequest               = core.UUIDSRequest
	UpdateTokenLastUsedRequest = core.UpdateTokenLastUsedRequest
	UseBackupCodeRequest       = core.UseBackupCodeRequest
	UserInfo                   = core.UserInfo
	UserListRequest            = core.UserListRequest
	UserListResponse           = core.UserListResponse
	VerifyTotpCodeRequest      = core.VerifyTotpCodeRequest
	VerifyTotpCodeResponse     = core.VerifyTotpCodeResponse
	VerifyTotpSetupRequest     = core.VerifyTotpSetupRequest

	TokenService interface {
		// 创建Token
		CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*TokenInfo, error)
		// 根据Token值获取Token信息
		GetTokenByValue(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*TokenInfo, error)
		// 更新Token
		UpdateToken(ctx context.Context, in *TokenInfo, opts ...grpc.CallOption) (*TokenInfo, error)
		// 删除Token
		DeleteToken(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*BaseResponse, error)
		// 获取Token列表
		ListToken(ctx context.Context, in *TokenListRequest, opts ...grpc.CallOption) (*TokenListResponse, error)
		// 清理过期Token
		CleanExpiredTokens(ctx context.Context, in *CleanExpiredTokensRequest, opts ...grpc.CallOption) (*CleanExpiredTokensResponse, error)
		// 更新Token最后使用时间
		UpdateTokenLastUsed(ctx context.Context, in *UpdateTokenLastUsedRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	}

	defaultTokenService struct {
		cli zrpc.Client
	}
)

func NewTokenService(cli zrpc.Client) TokenService {
	return &defaultTokenService{
		cli: cli,
	}
}

// 创建Token
func (m *defaultTokenService) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*TokenInfo, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.CreateToken(ctx, in, opts...)
}

// 根据Token值获取Token信息
func (m *defaultTokenService) GetTokenByValue(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*TokenInfo, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.GetTokenByValue(ctx, in, opts...)
}

// 更新Token
func (m *defaultTokenService) UpdateToken(ctx context.Context, in *TokenInfo, opts ...grpc.CallOption) (*TokenInfo, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.UpdateToken(ctx, in, opts...)
}

// 删除Token
func (m *defaultTokenService) DeleteToken(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.DeleteToken(ctx, in, opts...)
}

// 获取Token列表
func (m *defaultTokenService) ListToken(ctx context.Context, in *TokenListRequest, opts ...grpc.CallOption) (*TokenListResponse, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.ListToken(ctx, in, opts...)
}

// 清理过期Token
func (m *defaultTokenService) CleanExpiredTokens(ctx context.Context, in *CleanExpiredTokensRequest, opts ...grpc.CallOption) (*CleanExpiredTokensResponse, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.CleanExpiredTokens(ctx, in, opts...)
}

// 更新Token最后使用时间
func (m *defaultTokenService) UpdateTokenLastUsed(ctx context.Context, in *UpdateTokenLastUsedRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := core.NewTokenServiceClient(m.cli.Conn())
	return client.UpdateTokenLastUsed(ctx, in, opts...)
}
