// Code generated by ent, DO NOT EDIT.

package useroauth

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wenpiner/last-admin-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldUserID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldProviderID, v))
}

// OauthID applies equality check predicate on the "oauth_id" field. It's identical to OauthIDEQ.
func OauthID(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldOauthID, v))
}

// OauthToken applies equality check predicate on the "oauth_token" field. It's identical to OauthTokenEQ.
func OauthToken(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldOauthToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldRefreshToken, v))
}

// TokenExpiresAt applies equality check predicate on the "token_expires_at" field. It's identical to TokenExpiresAtEQ.
func TokenExpiresAt(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uint32) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldProviderID, vs...))
}

// OauthIDEQ applies the EQ predicate on the "oauth_id" field.
func OauthIDEQ(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldOauthID, v))
}

// OauthIDNEQ applies the NEQ predicate on the "oauth_id" field.
func OauthIDNEQ(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldOauthID, v))
}

// OauthIDIn applies the In predicate on the "oauth_id" field.
func OauthIDIn(vs ...string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldOauthID, vs...))
}

// OauthIDNotIn applies the NotIn predicate on the "oauth_id" field.
func OauthIDNotIn(vs ...string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldOauthID, vs...))
}

// OauthIDGT applies the GT predicate on the "oauth_id" field.
func OauthIDGT(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldOauthID, v))
}

// OauthIDGTE applies the GTE predicate on the "oauth_id" field.
func OauthIDGTE(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldOauthID, v))
}

// OauthIDLT applies the LT predicate on the "oauth_id" field.
func OauthIDLT(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldOauthID, v))
}

// OauthIDLTE applies the LTE predicate on the "oauth_id" field.
func OauthIDLTE(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldOauthID, v))
}

// OauthIDContains applies the Contains predicate on the "oauth_id" field.
func OauthIDContains(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldContains(FieldOauthID, v))
}

// OauthIDHasPrefix applies the HasPrefix predicate on the "oauth_id" field.
func OauthIDHasPrefix(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldHasPrefix(FieldOauthID, v))
}

// OauthIDHasSuffix applies the HasSuffix predicate on the "oauth_id" field.
func OauthIDHasSuffix(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldHasSuffix(FieldOauthID, v))
}

// OauthIDEqualFold applies the EqualFold predicate on the "oauth_id" field.
func OauthIDEqualFold(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEqualFold(FieldOauthID, v))
}

// OauthIDContainsFold applies the ContainsFold predicate on the "oauth_id" field.
func OauthIDContainsFold(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldContainsFold(FieldOauthID, v))
}

// OauthDataIsNil applies the IsNil predicate on the "oauth_data" field.
func OauthDataIsNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIsNull(FieldOauthData))
}

// OauthDataNotNil applies the NotNil predicate on the "oauth_data" field.
func OauthDataNotNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotNull(FieldOauthData))
}

// OauthTokenEQ applies the EQ predicate on the "oauth_token" field.
func OauthTokenEQ(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldOauthToken, v))
}

// OauthTokenNEQ applies the NEQ predicate on the "oauth_token" field.
func OauthTokenNEQ(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldOauthToken, v))
}

// OauthTokenIn applies the In predicate on the "oauth_token" field.
func OauthTokenIn(vs ...string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldOauthToken, vs...))
}

// OauthTokenNotIn applies the NotIn predicate on the "oauth_token" field.
func OauthTokenNotIn(vs ...string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldOauthToken, vs...))
}

// OauthTokenGT applies the GT predicate on the "oauth_token" field.
func OauthTokenGT(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldOauthToken, v))
}

// OauthTokenGTE applies the GTE predicate on the "oauth_token" field.
func OauthTokenGTE(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldOauthToken, v))
}

// OauthTokenLT applies the LT predicate on the "oauth_token" field.
func OauthTokenLT(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldOauthToken, v))
}

// OauthTokenLTE applies the LTE predicate on the "oauth_token" field.
func OauthTokenLTE(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldOauthToken, v))
}

// OauthTokenContains applies the Contains predicate on the "oauth_token" field.
func OauthTokenContains(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldContains(FieldOauthToken, v))
}

// OauthTokenHasPrefix applies the HasPrefix predicate on the "oauth_token" field.
func OauthTokenHasPrefix(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldHasPrefix(FieldOauthToken, v))
}

// OauthTokenHasSuffix applies the HasSuffix predicate on the "oauth_token" field.
func OauthTokenHasSuffix(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldHasSuffix(FieldOauthToken, v))
}

// OauthTokenIsNil applies the IsNil predicate on the "oauth_token" field.
func OauthTokenIsNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIsNull(FieldOauthToken))
}

// OauthTokenNotNil applies the NotNil predicate on the "oauth_token" field.
func OauthTokenNotNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotNull(FieldOauthToken))
}

// OauthTokenEqualFold applies the EqualFold predicate on the "oauth_token" field.
func OauthTokenEqualFold(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEqualFold(FieldOauthToken, v))
}

// OauthTokenContainsFold applies the ContainsFold predicate on the "oauth_token" field.
func OauthTokenContainsFold(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldContainsFold(FieldOauthToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotNull(FieldRefreshToken))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldContainsFold(FieldRefreshToken, v))
}

// TokenExpiresAtEQ applies the EQ predicate on the "token_expires_at" field.
func TokenExpiresAtEQ(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtNEQ applies the NEQ predicate on the "token_expires_at" field.
func TokenExpiresAtNEQ(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIn applies the In predicate on the "token_expires_at" field.
func TokenExpiresAtIn(vs ...time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtNotIn applies the NotIn predicate on the "token_expires_at" field.
func TokenExpiresAtNotIn(vs ...time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtGT applies the GT predicate on the "token_expires_at" field.
func TokenExpiresAtGT(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtGTE applies the GTE predicate on the "token_expires_at" field.
func TokenExpiresAtGTE(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldGTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLT applies the LT predicate on the "token_expires_at" field.
func TokenExpiresAtLT(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLTE applies the LTE predicate on the "token_expires_at" field.
func TokenExpiresAtLTE(v time.Time) predicate.UserOauth {
	return predicate.UserOauth(sql.FieldLTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIsNil applies the IsNil predicate on the "token_expires_at" field.
func TokenExpiresAtIsNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldIsNull(FieldTokenExpiresAt))
}

// TokenExpiresAtNotNil applies the NotNil predicate on the "token_expires_at" field.
func TokenExpiresAtNotNil() predicate.UserOauth {
	return predicate.UserOauth(sql.FieldNotNull(FieldTokenExpiresAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserOauth {
	return predicate.UserOauth(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserOauth {
	return predicate.UserOauth(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.UserOauth {
	return predicate.UserOauth(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.OauthProvider) predicate.UserOauth {
	return predicate.UserOauth(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserOauth) predicate.UserOauth {
	return predicate.UserOauth(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserOauth) predicate.UserOauth {
	return predicate.UserOauth(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserOauth) predicate.UserOauth {
	return predicate.UserOauth(sql.NotPredicates(p))
}
