// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wenpiner/last-admin-core/rpc/ent/department"
	"github.com/wenpiner/last-admin-core/rpc/ent/predicate"
	"github.com/wenpiner/last-admin-core/rpc/ent/user"
)

// DepartmentUpdate is the builder for updating Department entities.
type DepartmentUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentMutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (_u *DepartmentUpdate) Where(ps ...predicate.Department) *DepartmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepartmentUpdate) SetUpdatedAt(v time.Time) *DepartmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DepartmentUpdate) SetDeletedAt(v time.Time) *DepartmentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDeletedAt(v *time.Time) *DepartmentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DepartmentUpdate) ClearDeletedAt() *DepartmentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetState sets the "state" field.
func (_u *DepartmentUpdate) SetState(v bool) *DepartmentUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableState(v *bool) *DepartmentUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *DepartmentUpdate) ClearState() *DepartmentUpdate {
	_u.mutation.ClearState()
	return _u
}

// SetSort sets the "sort" field.
func (_u *DepartmentUpdate) SetSort(v int32) *DepartmentUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableSort(v *int32) *DepartmentUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DepartmentUpdate) AddSort(v int32) *DepartmentUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetDeptName sets the "dept_name" field.
func (_u *DepartmentUpdate) SetDeptName(v string) *DepartmentUpdate {
	_u.mutation.SetDeptName(v)
	return _u
}

// SetNillableDeptName sets the "dept_name" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDeptName(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetDeptName(*v)
	}
	return _u
}

// SetDeptCode sets the "dept_code" field.
func (_u *DepartmentUpdate) SetDeptCode(v string) *DepartmentUpdate {
	_u.mutation.SetDeptCode(v)
	return _u
}

// SetNillableDeptCode sets the "dept_code" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDeptCode(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetDeptCode(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DepartmentUpdate) SetParentID(v uint32) *DepartmentUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableParentID(v *uint32) *DepartmentUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *DepartmentUpdate) ClearParentID() *DepartmentUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetLeaderUserID sets the "leader_user_id" field.
func (_u *DepartmentUpdate) SetLeaderUserID(v uuid.UUID) *DepartmentUpdate {
	_u.mutation.SetLeaderUserID(v)
	return _u
}

// SetNillableLeaderUserID sets the "leader_user_id" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableLeaderUserID(v *uuid.UUID) *DepartmentUpdate {
	if v != nil {
		_u.SetLeaderUserID(*v)
	}
	return _u
}

// ClearLeaderUserID clears the value of the "leader_user_id" field.
func (_u *DepartmentUpdate) ClearLeaderUserID() *DepartmentUpdate {
	_u.mutation.ClearLeaderUserID()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DepartmentUpdate) SetDescription(v string) *DepartmentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDescription(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DepartmentUpdate) ClearDescription() *DepartmentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetParent sets the "parent" edge to the Department entity.
func (_u *DepartmentUpdate) SetParent(v *Department) *DepartmentUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Department entity by IDs.
func (_u *DepartmentUpdate) AddChildIDs(ids ...uint32) *DepartmentUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Department entity.
func (_u *DepartmentUpdate) AddChildren(v ...*Department) *DepartmentUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *DepartmentUpdate) AddUserIDs(ids ...uuid.UUID) *DepartmentUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *DepartmentUpdate) AddUsers(v ...*User) *DepartmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// SetLeaderID sets the "leader" edge to the User entity by ID.
func (_u *DepartmentUpdate) SetLeaderID(id uuid.UUID) *DepartmentUpdate {
	_u.mutation.SetLeaderID(id)
	return _u
}

// SetNillableLeaderID sets the "leader" edge to the User entity by ID if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableLeaderID(id *uuid.UUID) *DepartmentUpdate {
	if id != nil {
		_u = _u.SetLeaderID(*id)
	}
	return _u
}

// SetLeader sets the "leader" edge to the User entity.
func (_u *DepartmentUpdate) SetLeader(v *User) *DepartmentUpdate {
	return _u.SetLeaderID(v.ID)
}

// Mutation returns the DepartmentMutation object of the builder.
func (_u *DepartmentUpdate) Mutation() *DepartmentMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Department entity.
func (_u *DepartmentUpdate) ClearParent() *DepartmentUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Department entity.
func (_u *DepartmentUpdate) ClearChildren() *DepartmentUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Department entities by IDs.
func (_u *DepartmentUpdate) RemoveChildIDs(ids ...uint32) *DepartmentUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Department entities.
func (_u *DepartmentUpdate) RemoveChildren(v ...*Department) *DepartmentUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *DepartmentUpdate) ClearUsers() *DepartmentUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *DepartmentUpdate) RemoveUserIDs(ids ...uuid.UUID) *DepartmentUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *DepartmentUpdate) RemoveUsers(v ...*User) *DepartmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearLeader clears the "leader" edge to the User entity.
func (_u *DepartmentUpdate) ClearLeader() *DepartmentUpdate {
	_u.mutation.ClearLeader()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepartmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepartmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepartmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := department.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepartmentUpdate) check() error {
	if v, ok := _u.mutation.DeptName(); ok {
		if err := department.DeptNameValidator(v); err != nil {
			return &ValidationError{Name: "dept_name", err: fmt.Errorf(`ent: validator failed for field "Department.dept_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeptCode(); ok {
		if err := department.DeptCodeValidator(v); err != nil {
			return &ValidationError{Name: "dept_code", err: fmt.Errorf(`ent: validator failed for field "Department.dept_code": %w`, err)}
		}
	}
	return nil
}

func (_u *DepartmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(department.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(department.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(department.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(department.FieldState, field.TypeBool, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(department.FieldState, field.TypeBool)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(department.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(department.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DeptName(); ok {
		_spec.SetField(department.FieldDeptName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeptCode(); ok {
		_spec.SetField(department.FieldDeptCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(department.FieldDescription, field.TypeString)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.LeaderTable,
			Columns: []string{department.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.LeaderTable,
			Columns: []string{department.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepartmentUpdateOne is the builder for updating a single Department entity.
type DepartmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepartmentUpdateOne) SetUpdatedAt(v time.Time) *DepartmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DepartmentUpdateOne) SetDeletedAt(v time.Time) *DepartmentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDeletedAt(v *time.Time) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DepartmentUpdateOne) ClearDeletedAt() *DepartmentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetState sets the "state" field.
func (_u *DepartmentUpdateOne) SetState(v bool) *DepartmentUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableState(v *bool) *DepartmentUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *DepartmentUpdateOne) ClearState() *DepartmentUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// SetSort sets the "sort" field.
func (_u *DepartmentUpdateOne) SetSort(v int32) *DepartmentUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableSort(v *int32) *DepartmentUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DepartmentUpdateOne) AddSort(v int32) *DepartmentUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetDeptName sets the "dept_name" field.
func (_u *DepartmentUpdateOne) SetDeptName(v string) *DepartmentUpdateOne {
	_u.mutation.SetDeptName(v)
	return _u
}

// SetNillableDeptName sets the "dept_name" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDeptName(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDeptName(*v)
	}
	return _u
}

// SetDeptCode sets the "dept_code" field.
func (_u *DepartmentUpdateOne) SetDeptCode(v string) *DepartmentUpdateOne {
	_u.mutation.SetDeptCode(v)
	return _u
}

// SetNillableDeptCode sets the "dept_code" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDeptCode(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDeptCode(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DepartmentUpdateOne) SetParentID(v uint32) *DepartmentUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableParentID(v *uint32) *DepartmentUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *DepartmentUpdateOne) ClearParentID() *DepartmentUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetLeaderUserID sets the "leader_user_id" field.
func (_u *DepartmentUpdateOne) SetLeaderUserID(v uuid.UUID) *DepartmentUpdateOne {
	_u.mutation.SetLeaderUserID(v)
	return _u
}

// SetNillableLeaderUserID sets the "leader_user_id" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableLeaderUserID(v *uuid.UUID) *DepartmentUpdateOne {
	if v != nil {
		_u.SetLeaderUserID(*v)
	}
	return _u
}

// ClearLeaderUserID clears the value of the "leader_user_id" field.
func (_u *DepartmentUpdateOne) ClearLeaderUserID() *DepartmentUpdateOne {
	_u.mutation.ClearLeaderUserID()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DepartmentUpdateOne) SetDescription(v string) *DepartmentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDescription(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DepartmentUpdateOne) ClearDescription() *DepartmentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetParent sets the "parent" edge to the Department entity.
func (_u *DepartmentUpdateOne) SetParent(v *Department) *DepartmentUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Department entity by IDs.
func (_u *DepartmentUpdateOne) AddChildIDs(ids ...uint32) *DepartmentUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Department entity.
func (_u *DepartmentUpdateOne) AddChildren(v ...*Department) *DepartmentUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *DepartmentUpdateOne) AddUserIDs(ids ...uuid.UUID) *DepartmentUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *DepartmentUpdateOne) AddUsers(v ...*User) *DepartmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// SetLeaderID sets the "leader" edge to the User entity by ID.
func (_u *DepartmentUpdateOne) SetLeaderID(id uuid.UUID) *DepartmentUpdateOne {
	_u.mutation.SetLeaderID(id)
	return _u
}

// SetNillableLeaderID sets the "leader" edge to the User entity by ID if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableLeaderID(id *uuid.UUID) *DepartmentUpdateOne {
	if id != nil {
		_u = _u.SetLeaderID(*id)
	}
	return _u
}

// SetLeader sets the "leader" edge to the User entity.
func (_u *DepartmentUpdateOne) SetLeader(v *User) *DepartmentUpdateOne {
	return _u.SetLeaderID(v.ID)
}

// Mutation returns the DepartmentMutation object of the builder.
func (_u *DepartmentUpdateOne) Mutation() *DepartmentMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Department entity.
func (_u *DepartmentUpdateOne) ClearParent() *DepartmentUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Department entity.
func (_u *DepartmentUpdateOne) ClearChildren() *DepartmentUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Department entities by IDs.
func (_u *DepartmentUpdateOne) RemoveChildIDs(ids ...uint32) *DepartmentUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Department entities.
func (_u *DepartmentUpdateOne) RemoveChildren(v ...*Department) *DepartmentUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *DepartmentUpdateOne) ClearUsers() *DepartmentUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *DepartmentUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *DepartmentUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *DepartmentUpdateOne) RemoveUsers(v ...*User) *DepartmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearLeader clears the "leader" edge to the User entity.
func (_u *DepartmentUpdateOne) ClearLeader() *DepartmentUpdateOne {
	_u.mutation.ClearLeader()
	return _u
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (_u *DepartmentUpdateOne) Where(ps ...predicate.Department) *DepartmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepartmentUpdateOne) Select(field string, fields ...string) *DepartmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Department entity.
func (_u *DepartmentUpdateOne) Save(ctx context.Context) (*Department, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentUpdateOne) SaveX(ctx context.Context) *Department {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepartmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepartmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := department.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepartmentUpdateOne) check() error {
	if v, ok := _u.mutation.DeptName(); ok {
		if err := department.DeptNameValidator(v); err != nil {
			return &ValidationError{Name: "dept_name", err: fmt.Errorf(`ent: validator failed for field "Department.dept_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeptCode(); ok {
		if err := department.DeptCodeValidator(v); err != nil {
			return &ValidationError{Name: "dept_code", err: fmt.Errorf(`ent: validator failed for field "Department.dept_code": %w`, err)}
		}
	}
	return nil
}

func (_u *DepartmentUpdateOne) sqlSave(ctx context.Context) (_node *Department, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Department.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, department.FieldID)
		for _, f := range fields {
			if !department.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != department.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(department.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(department.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(department.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(department.FieldState, field.TypeBool, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(department.FieldState, field.TypeBool)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(department.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(department.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DeptName(); ok {
		_spec.SetField(department.FieldDeptName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeptCode(); ok {
		_spec.SetField(department.FieldDeptCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(department.FieldDescription, field.TypeString)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.LeaderTable,
			Columns: []string{department.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.LeaderTable,
			Columns: []string{department.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Department{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
