// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wenpiner/last-admin-core/rpc/ent/dictitem"
	"github.com/wenpiner/last-admin-core/rpc/ent/dicttype"
)

// DictItemCreate is the builder for creating a DictItem entity.
type DictItemCreate struct {
	config
	mutation *DictItemMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DictItemCreate) SetCreatedAt(v time.Time) *DictItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableCreatedAt(v *time.Time) *DictItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DictItemCreate) SetUpdatedAt(v time.Time) *DictItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableUpdatedAt(v *time.Time) *DictItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DictItemCreate) SetDeletedAt(v time.Time) *DictItemCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableDeletedAt(v *time.Time) *DictItemCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *DictItemCreate) SetState(v bool) *DictItemCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableState(v *bool) *DictItemCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetItemLabel sets the "item_label" field.
func (_c *DictItemCreate) SetItemLabel(v string) *DictItemCreate {
	_c.mutation.SetItemLabel(v)
	return _c
}

// SetItemValue sets the "item_value" field.
func (_c *DictItemCreate) SetItemValue(v string) *DictItemCreate {
	_c.mutation.SetItemValue(v)
	return _c
}

// SetItemColor sets the "item_color" field.
func (_c *DictItemCreate) SetItemColor(v string) *DictItemCreate {
	_c.mutation.SetItemColor(v)
	return _c
}

// SetNillableItemColor sets the "item_color" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableItemColor(v *string) *DictItemCreate {
	if v != nil {
		_c.SetItemColor(*v)
	}
	return _c
}

// SetItemCSS sets the "item_css" field.
func (_c *DictItemCreate) SetItemCSS(v string) *DictItemCreate {
	_c.mutation.SetItemCSS(v)
	return _c
}

// SetNillableItemCSS sets the "item_css" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableItemCSS(v *string) *DictItemCreate {
	if v != nil {
		_c.SetItemCSS(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *DictItemCreate) SetSortOrder(v int) *DictItemCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableSortOrder(v *int) *DictItemCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *DictItemCreate) SetDescription(v string) *DictItemCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableDescription(v *string) *DictItemCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDictTypeID sets the "dict_type_id" field.
func (_c *DictItemCreate) SetDictTypeID(v uint32) *DictItemCreate {
	_c.mutation.SetDictTypeID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DictItemCreate) SetID(v uint32) *DictItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDictType sets the "dict_type" edge to the DictType entity.
func (_c *DictItemCreate) SetDictType(v *DictType) *DictItemCreate {
	return _c.SetDictTypeID(v.ID)
}

// Mutation returns the DictItemMutation object of the builder.
func (_c *DictItemCreate) Mutation() *DictItemMutation {
	return _c.mutation
}

// Save creates the DictItem in the database.
func (_c *DictItemCreate) Save(ctx context.Context) (*DictItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictItemCreate) SaveX(ctx context.Context) *DictItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dictitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dictitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := dictitem.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := dictitem.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DictItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DictItem.updated_at"`)}
	}
	if _, ok := _c.mutation.ItemLabel(); !ok {
		return &ValidationError{Name: "item_label", err: errors.New(`ent: missing required field "DictItem.item_label"`)}
	}
	if v, ok := _c.mutation.ItemLabel(); ok {
		if err := dictitem.ItemLabelValidator(v); err != nil {
			return &ValidationError{Name: "item_label", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ItemValue(); !ok {
		return &ValidationError{Name: "item_value", err: errors.New(`ent: missing required field "DictItem.item_value"`)}
	}
	if v, ok := _c.mutation.ItemValue(); ok {
		if err := dictitem.ItemValueValidator(v); err != nil {
			return &ValidationError{Name: "item_value", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_value": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ItemColor(); ok {
		if err := dictitem.ItemColorValidator(v); err != nil {
			return &ValidationError{Name: "item_color", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_color": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ItemCSS(); ok {
		if err := dictitem.ItemCSSValidator(v); err != nil {
			return &ValidationError{Name: "item_css", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_css": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "DictItem.sort_order"`)}
	}
	if _, ok := _c.mutation.DictTypeID(); !ok {
		return &ValidationError{Name: "dict_type_id", err: errors.New(`ent: missing required field "DictItem.dict_type_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := dictitem.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DictItem.id": %w`, err)}
		}
	}
	if len(_c.mutation.DictTypeIDs()) == 0 {
		return &ValidationError{Name: "dict_type", err: errors.New(`ent: missing required edge "DictItem.dict_type"`)}
	}
	return nil
}

func (_c *DictItemCreate) sqlSave(ctx context.Context) (*DictItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictItemCreate) createSpec() (*DictItem, *sqlgraph.CreateSpec) {
	var (
		_node = &DictItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictitem.Table, sqlgraph.NewFieldSpec(dictitem.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dictitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dictitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(dictitem.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(dictitem.FieldState, field.TypeBool, value)
		_node.State = value
	}
	if value, ok := _c.mutation.ItemLabel(); ok {
		_spec.SetField(dictitem.FieldItemLabel, field.TypeString, value)
		_node.ItemLabel = value
	}
	if value, ok := _c.mutation.ItemValue(); ok {
		_spec.SetField(dictitem.FieldItemValue, field.TypeString, value)
		_node.ItemValue = value
	}
	if value, ok := _c.mutation.ItemColor(); ok {
		_spec.SetField(dictitem.FieldItemColor, field.TypeString, value)
		_node.ItemColor = &value
	}
	if value, ok := _c.mutation.ItemCSS(); ok {
		_spec.SetField(dictitem.FieldItemCSS, field.TypeString, value)
		_node.ItemCSS = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(dictitem.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(dictitem.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if nodes := _c.mutation.DictTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dictitem.DictTypeTable,
			Columns: []string{dictitem.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DictTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DictItemCreateBulk is the builder for creating many DictItem entities in bulk.
type DictItemCreateBulk struct {
	config
	err      error
	builders []*DictItemCreate
}

// Save creates the DictItem entities in the database.
func (_c *DictItemCreateBulk) Save(ctx context.Context) ([]*DictItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DictItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictItemCreateBulk) SaveX(ctx context.Context) []*DictItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
