// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wenpiner/last-admin-core/rpc/ent/dictitem"
	"github.com/wenpiner/last-admin-core/rpc/ent/dicttype"
	"github.com/wenpiner/last-admin-core/rpc/ent/predicate"
)

// DictItemUpdate is the builder for updating DictItem entities.
type DictItemUpdate struct {
	config
	hooks    []Hook
	mutation *DictItemMutation
}

// Where appends a list predicates to the DictItemUpdate builder.
func (_u *DictItemUpdate) Where(ps ...predicate.DictItem) *DictItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictItemUpdate) SetUpdatedAt(v time.Time) *DictItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictItemUpdate) SetDeletedAt(v time.Time) *DictItemUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableDeletedAt(v *time.Time) *DictItemUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictItemUpdate) ClearDeletedAt() *DictItemUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetState sets the "state" field.
func (_u *DictItemUpdate) SetState(v bool) *DictItemUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableState(v *bool) *DictItemUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *DictItemUpdate) ClearState() *DictItemUpdate {
	_u.mutation.ClearState()
	return _u
}

// SetItemLabel sets the "item_label" field.
func (_u *DictItemUpdate) SetItemLabel(v string) *DictItemUpdate {
	_u.mutation.SetItemLabel(v)
	return _u
}

// SetNillableItemLabel sets the "item_label" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableItemLabel(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetItemLabel(*v)
	}
	return _u
}

// SetItemValue sets the "item_value" field.
func (_u *DictItemUpdate) SetItemValue(v string) *DictItemUpdate {
	_u.mutation.SetItemValue(v)
	return _u
}

// SetNillableItemValue sets the "item_value" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableItemValue(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetItemValue(*v)
	}
	return _u
}

// SetItemColor sets the "item_color" field.
func (_u *DictItemUpdate) SetItemColor(v string) *DictItemUpdate {
	_u.mutation.SetItemColor(v)
	return _u
}

// SetNillableItemColor sets the "item_color" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableItemColor(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetItemColor(*v)
	}
	return _u
}

// ClearItemColor clears the value of the "item_color" field.
func (_u *DictItemUpdate) ClearItemColor() *DictItemUpdate {
	_u.mutation.ClearItemColor()
	return _u
}

// SetItemCSS sets the "item_css" field.
func (_u *DictItemUpdate) SetItemCSS(v string) *DictItemUpdate {
	_u.mutation.SetItemCSS(v)
	return _u
}

// SetNillableItemCSS sets the "item_css" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableItemCSS(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetItemCSS(*v)
	}
	return _u
}

// ClearItemCSS clears the value of the "item_css" field.
func (_u *DictItemUpdate) ClearItemCSS() *DictItemUpdate {
	_u.mutation.ClearItemCSS()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DictItemUpdate) SetSortOrder(v int) *DictItemUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableSortOrder(v *int) *DictItemUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DictItemUpdate) AddSortOrder(v int) *DictItemUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictItemUpdate) SetDescription(v string) *DictItemUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableDescription(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DictItemUpdate) ClearDescription() *DictItemUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDictTypeID sets the "dict_type_id" field.
func (_u *DictItemUpdate) SetDictTypeID(v uint32) *DictItemUpdate {
	_u.mutation.SetDictTypeID(v)
	return _u
}

// SetNillableDictTypeID sets the "dict_type_id" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableDictTypeID(v *uint32) *DictItemUpdate {
	if v != nil {
		_u.SetDictTypeID(*v)
	}
	return _u
}

// SetDictType sets the "dict_type" edge to the DictType entity.
func (_u *DictItemUpdate) SetDictType(v *DictType) *DictItemUpdate {
	return _u.SetDictTypeID(v.ID)
}

// Mutation returns the DictItemMutation object of the builder.
func (_u *DictItemUpdate) Mutation() *DictItemMutation {
	return _u.mutation
}

// ClearDictType clears the "dict_type" edge to the DictType entity.
func (_u *DictItemUpdate) ClearDictType() *DictItemUpdate {
	_u.mutation.ClearDictType()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictItemUpdate) check() error {
	if v, ok := _u.mutation.ItemLabel(); ok {
		if err := dictitem.ItemLabelValidator(v); err != nil {
			return &ValidationError{Name: "item_label", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemValue(); ok {
		if err := dictitem.ItemValueValidator(v); err != nil {
			return &ValidationError{Name: "item_value", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemColor(); ok {
		if err := dictitem.ItemColorValidator(v); err != nil {
			return &ValidationError{Name: "item_color", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemCSS(); ok {
		if err := dictitem.ItemCSSValidator(v); err != nil {
			return &ValidationError{Name: "item_css", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_css": %w`, err)}
		}
	}
	if _u.mutation.DictTypeCleared() && len(_u.mutation.DictTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DictItem.dict_type"`)
	}
	return nil
}

func (_u *DictItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictitem.Table, dictitem.Columns, sqlgraph.NewFieldSpec(dictitem.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(dictitem.FieldState, field.TypeBool, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(dictitem.FieldState, field.TypeBool)
	}
	if value, ok := _u.mutation.ItemLabel(); ok {
		_spec.SetField(dictitem.FieldItemLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemValue(); ok {
		_spec.SetField(dictitem.FieldItemValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemColor(); ok {
		_spec.SetField(dictitem.FieldItemColor, field.TypeString, value)
	}
	if _u.mutation.ItemColorCleared() {
		_spec.ClearField(dictitem.FieldItemColor, field.TypeString)
	}
	if value, ok := _u.mutation.ItemCSS(); ok {
		_spec.SetField(dictitem.FieldItemCSS, field.TypeString, value)
	}
	if _u.mutation.ItemCSSCleared() {
		_spec.ClearField(dictitem.FieldItemCSS, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(dictitem.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(dictitem.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dictitem.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dictitem.FieldDescription, field.TypeString)
	}
	if _u.mutation.DictTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dictitem.DictTypeTable,
			Columns: []string{dictitem.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dictitem.DictTypeTable,
			Columns: []string{dictitem.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictItemUpdateOne is the builder for updating a single DictItem entity.
type DictItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictItemUpdateOne) SetUpdatedAt(v time.Time) *DictItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictItemUpdateOne) SetDeletedAt(v time.Time) *DictItemUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableDeletedAt(v *time.Time) *DictItemUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictItemUpdateOne) ClearDeletedAt() *DictItemUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetState sets the "state" field.
func (_u *DictItemUpdateOne) SetState(v bool) *DictItemUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableState(v *bool) *DictItemUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *DictItemUpdateOne) ClearState() *DictItemUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// SetItemLabel sets the "item_label" field.
func (_u *DictItemUpdateOne) SetItemLabel(v string) *DictItemUpdateOne {
	_u.mutation.SetItemLabel(v)
	return _u
}

// SetNillableItemLabel sets the "item_label" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableItemLabel(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetItemLabel(*v)
	}
	return _u
}

// SetItemValue sets the "item_value" field.
func (_u *DictItemUpdateOne) SetItemValue(v string) *DictItemUpdateOne {
	_u.mutation.SetItemValue(v)
	return _u
}

// SetNillableItemValue sets the "item_value" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableItemValue(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetItemValue(*v)
	}
	return _u
}

// SetItemColor sets the "item_color" field.
func (_u *DictItemUpdateOne) SetItemColor(v string) *DictItemUpdateOne {
	_u.mutation.SetItemColor(v)
	return _u
}

// SetNillableItemColor sets the "item_color" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableItemColor(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetItemColor(*v)
	}
	return _u
}

// ClearItemColor clears the value of the "item_color" field.
func (_u *DictItemUpdateOne) ClearItemColor() *DictItemUpdateOne {
	_u.mutation.ClearItemColor()
	return _u
}

// SetItemCSS sets the "item_css" field.
func (_u *DictItemUpdateOne) SetItemCSS(v string) *DictItemUpdateOne {
	_u.mutation.SetItemCSS(v)
	return _u
}

// SetNillableItemCSS sets the "item_css" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableItemCSS(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetItemCSS(*v)
	}
	return _u
}

// ClearItemCSS clears the value of the "item_css" field.
func (_u *DictItemUpdateOne) ClearItemCSS() *DictItemUpdateOne {
	_u.mutation.ClearItemCSS()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DictItemUpdateOne) SetSortOrder(v int) *DictItemUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableSortOrder(v *int) *DictItemUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DictItemUpdateOne) AddSortOrder(v int) *DictItemUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictItemUpdateOne) SetDescription(v string) *DictItemUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableDescription(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DictItemUpdateOne) ClearDescription() *DictItemUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDictTypeID sets the "dict_type_id" field.
func (_u *DictItemUpdateOne) SetDictTypeID(v uint32) *DictItemUpdateOne {
	_u.mutation.SetDictTypeID(v)
	return _u
}

// SetNillableDictTypeID sets the "dict_type_id" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableDictTypeID(v *uint32) *DictItemUpdateOne {
	if v != nil {
		_u.SetDictTypeID(*v)
	}
	return _u
}

// SetDictType sets the "dict_type" edge to the DictType entity.
func (_u *DictItemUpdateOne) SetDictType(v *DictType) *DictItemUpdateOne {
	return _u.SetDictTypeID(v.ID)
}

// Mutation returns the DictItemMutation object of the builder.
func (_u *DictItemUpdateOne) Mutation() *DictItemMutation {
	return _u.mutation
}

// ClearDictType clears the "dict_type" edge to the DictType entity.
func (_u *DictItemUpdateOne) ClearDictType() *DictItemUpdateOne {
	_u.mutation.ClearDictType()
	return _u
}

// Where appends a list predicates to the DictItemUpdate builder.
func (_u *DictItemUpdateOne) Where(ps ...predicate.DictItem) *DictItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictItemUpdateOne) Select(field string, fields ...string) *DictItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictItem entity.
func (_u *DictItemUpdateOne) Save(ctx context.Context) (*DictItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictItemUpdateOne) SaveX(ctx context.Context) *DictItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictItemUpdateOne) check() error {
	if v, ok := _u.mutation.ItemLabel(); ok {
		if err := dictitem.ItemLabelValidator(v); err != nil {
			return &ValidationError{Name: "item_label", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemValue(); ok {
		if err := dictitem.ItemValueValidator(v); err != nil {
			return &ValidationError{Name: "item_value", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemColor(); ok {
		if err := dictitem.ItemColorValidator(v); err != nil {
			return &ValidationError{Name: "item_color", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemCSS(); ok {
		if err := dictitem.ItemCSSValidator(v); err != nil {
			return &ValidationError{Name: "item_css", err: fmt.Errorf(`ent: validator failed for field "DictItem.item_css": %w`, err)}
		}
	}
	if _u.mutation.DictTypeCleared() && len(_u.mutation.DictTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DictItem.dict_type"`)
	}
	return nil
}

func (_u *DictItemUpdateOne) sqlSave(ctx context.Context) (_node *DictItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictitem.Table, dictitem.Columns, sqlgraph.NewFieldSpec(dictitem.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictitem.FieldID)
		for _, f := range fields {
			if !dictitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(dictitem.FieldState, field.TypeBool, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(dictitem.FieldState, field.TypeBool)
	}
	if value, ok := _u.mutation.ItemLabel(); ok {
		_spec.SetField(dictitem.FieldItemLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemValue(); ok {
		_spec.SetField(dictitem.FieldItemValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemColor(); ok {
		_spec.SetField(dictitem.FieldItemColor, field.TypeString, value)
	}
	if _u.mutation.ItemColorCleared() {
		_spec.ClearField(dictitem.FieldItemColor, field.TypeString)
	}
	if value, ok := _u.mutation.ItemCSS(); ok {
		_spec.SetField(dictitem.FieldItemCSS, field.TypeString, value)
	}
	if _u.mutation.ItemCSSCleared() {
		_spec.ClearField(dictitem.FieldItemCSS, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(dictitem.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(dictitem.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dictitem.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dictitem.FieldDescription, field.TypeString)
	}
	if _u.mutation.DictTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dictitem.DictTypeTable,
			Columns: []string{dictitem.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dictitem.DictTypeTable,
			Columns: []string{dictitem.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DictItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
