// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/wenpiner/last-admin-core/rpc/ent/dictitem"
	"github.com/wenpiner/last-admin-core/rpc/ent/dicttype"
)

// 字典项表 / Dictionary item table
type DictItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// 创建时间 / Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间 / Update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间 / Deleted time
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 状态 / State
	State bool `json:"state,omitempty"`
	// 字典项标签 / Dictionary item label
	ItemLabel string `json:"item_label,omitempty"`
	// 字典项值 / Dictionary item value
	ItemValue string `json:"item_value,omitempty"`
	// 字典项颜色 / Dictionary item color
	ItemColor *string `json:"item_color,omitempty"`
	// 字典项CSS / Dictionary item CSS
	ItemCSS *string `json:"item_css,omitempty"`
	// 排序 / Sort order
	SortOrder int `json:"sort_order,omitempty"`
	// 字典项描述 / Dictionary item description
	Description *string `json:"description,omitempty"`
	// 字典类型ID / Dictionary type ID
	DictTypeID uint32 `json:"dict_type_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DictItemQuery when eager-loading is set.
	Edges        DictItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DictItemEdges holds the relations/edges for other nodes in the graph.
type DictItemEdges struct {
	// DictType holds the value of the dict_type edge.
	DictType *DictType `json:"dict_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DictTypeOrErr returns the DictType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DictItemEdges) DictTypeOrErr() (*DictType, error) {
	if e.DictType != nil {
		return e.DictType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dicttype.Label}
	}
	return nil, &NotLoadedError{edge: "dict_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DictItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dictitem.FieldState:
			values[i] = new(sql.NullBool)
		case dictitem.FieldID, dictitem.FieldSortOrder, dictitem.FieldDictTypeID:
			values[i] = new(sql.NullInt64)
		case dictitem.FieldItemLabel, dictitem.FieldItemValue, dictitem.FieldItemColor, dictitem.FieldItemCSS, dictitem.FieldDescription:
			values[i] = new(sql.NullString)
		case dictitem.FieldCreatedAt, dictitem.FieldUpdatedAt, dictitem.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DictItem fields.
func (_m *DictItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dictitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case dictitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dictitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dictitem.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case dictitem.FieldState:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.Bool
			}
		case dictitem.FieldItemLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_label", values[i])
			} else if value.Valid {
				_m.ItemLabel = value.String
			}
		case dictitem.FieldItemValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_value", values[i])
			} else if value.Valid {
				_m.ItemValue = value.String
			}
		case dictitem.FieldItemColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_color", values[i])
			} else if value.Valid {
				_m.ItemColor = new(string)
				*_m.ItemColor = value.String
			}
		case dictitem.FieldItemCSS:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_css", values[i])
			} else if value.Valid {
				_m.ItemCSS = new(string)
				*_m.ItemCSS = value.String
			}
		case dictitem.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case dictitem.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case dictitem.FieldDictTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dict_type_id", values[i])
			} else if value.Valid {
				_m.DictTypeID = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DictItem.
// This includes values selected through modifiers, order, etc.
func (_m *DictItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDictType queries the "dict_type" edge of the DictItem entity.
func (_m *DictItem) QueryDictType() *DictTypeQuery {
	return NewDictItemClient(_m.config).QueryDictType(_m)
}

// Update returns a builder for updating this DictItem.
// Note that you need to call DictItem.Unwrap() before calling this method if this DictItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DictItem) Update() *DictItemUpdateOne {
	return NewDictItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DictItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DictItem) Unwrap() *DictItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DictItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DictItem) String() string {
	var builder strings.Builder
	builder.WriteString("DictItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("item_label=")
	builder.WriteString(_m.ItemLabel)
	builder.WriteString(", ")
	builder.WriteString("item_value=")
	builder.WriteString(_m.ItemValue)
	builder.WriteString(", ")
	if v := _m.ItemColor; v != nil {
		builder.WriteString("item_color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ItemCSS; v != nil {
		builder.WriteString("item_css=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("dict_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DictTypeID))
	builder.WriteByte(')')
	return builder.String()
}

// DictItems is a parsable slice of DictItem.
type DictItems []*DictItem
