// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wenpiner/last-admin-core/rpc/ent/menu"
	"github.com/wenpiner/last-admin-core/rpc/ent/role"
)

// MenuCreate is the builder for creating a Menu entity.
type MenuCreate struct {
	config
	mutation *MenuMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MenuCreate) SetCreatedAt(v time.Time) *MenuCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MenuCreate) SetNillableCreatedAt(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MenuCreate) SetUpdatedAt(v time.Time) *MenuCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MenuCreate) SetNillableUpdatedAt(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *MenuCreate) SetState(v bool) *MenuCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *MenuCreate) SetNillableState(v *bool) *MenuCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *MenuCreate) SetSort(v int32) *MenuCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *MenuCreate) SetNillableSort(v *int32) *MenuCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetMenuCode sets the "menu_code" field.
func (_c *MenuCreate) SetMenuCode(v string) *MenuCreate {
	_c.mutation.SetMenuCode(v)
	return _c
}

// SetMenuName sets the "menu_name" field.
func (_c *MenuCreate) SetMenuName(v string) *MenuCreate {
	_c.mutation.SetMenuName(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *MenuCreate) SetParentID(v uint32) *MenuCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *MenuCreate) SetNillableParentID(v *uint32) *MenuCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetMenuPath sets the "menu_path" field.
func (_c *MenuCreate) SetMenuPath(v string) *MenuCreate {
	_c.mutation.SetMenuPath(v)
	return _c
}

// SetNillableMenuPath sets the "menu_path" field if the given value is not nil.
func (_c *MenuCreate) SetNillableMenuPath(v *string) *MenuCreate {
	if v != nil {
		_c.SetMenuPath(*v)
	}
	return _c
}

// SetComponent sets the "component" field.
func (_c *MenuCreate) SetComponent(v string) *MenuCreate {
	_c.mutation.SetComponent(v)
	return _c
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_c *MenuCreate) SetNillableComponent(v *string) *MenuCreate {
	if v != nil {
		_c.SetComponent(*v)
	}
	return _c
}

// SetRedirect sets the "redirect" field.
func (_c *MenuCreate) SetRedirect(v string) *MenuCreate {
	_c.mutation.SetRedirect(v)
	return _c
}

// SetNillableRedirect sets the "redirect" field if the given value is not nil.
func (_c *MenuCreate) SetNillableRedirect(v *string) *MenuCreate {
	if v != nil {
		_c.SetRedirect(*v)
	}
	return _c
}

// SetMenuLevel sets the "menu_level" field.
func (_c *MenuCreate) SetMenuLevel(v uint16) *MenuCreate {
	_c.mutation.SetMenuLevel(v)
	return _c
}

// SetNillableMenuLevel sets the "menu_level" field if the given value is not nil.
func (_c *MenuCreate) SetNillableMenuLevel(v *uint16) *MenuCreate {
	if v != nil {
		_c.SetMenuLevel(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *MenuCreate) SetIcon(v string) *MenuCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIcon(v *string) *MenuCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetPermission sets the "permission" field.
func (_c *MenuCreate) SetPermission(v string) *MenuCreate {
	_c.mutation.SetPermission(v)
	return _c
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_c *MenuCreate) SetNillablePermission(v *string) *MenuCreate {
	if v != nil {
		_c.SetPermission(*v)
	}
	return _c
}

// SetServiceName sets the "service_name" field.
func (_c *MenuCreate) SetServiceName(v string) *MenuCreate {
	_c.mutation.SetServiceName(v)
	return _c
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_c *MenuCreate) SetNillableServiceName(v *string) *MenuCreate {
	if v != nil {
		_c.SetServiceName(*v)
	}
	return _c
}

// SetMenuType sets the "menu_type" field.
func (_c *MenuCreate) SetMenuType(v string) *MenuCreate {
	_c.mutation.SetMenuType(v)
	return _c
}

// SetIsHidden sets the "is_hidden" field.
func (_c *MenuCreate) SetIsHidden(v bool) *MenuCreate {
	_c.mutation.SetIsHidden(v)
	return _c
}

// SetNillableIsHidden sets the "is_hidden" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsHidden(v *bool) *MenuCreate {
	if v != nil {
		_c.SetIsHidden(*v)
	}
	return _c
}

// SetIsBreadcrumb sets the "is_breadcrumb" field.
func (_c *MenuCreate) SetIsBreadcrumb(v bool) *MenuCreate {
	_c.mutation.SetIsBreadcrumb(v)
	return _c
}

// SetNillableIsBreadcrumb sets the "is_breadcrumb" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsBreadcrumb(v *bool) *MenuCreate {
	if v != nil {
		_c.SetIsBreadcrumb(*v)
	}
	return _c
}

// SetIsCache sets the "is_cache" field.
func (_c *MenuCreate) SetIsCache(v bool) *MenuCreate {
	_c.mutation.SetIsCache(v)
	return _c
}

// SetNillableIsCache sets the "is_cache" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsCache(v *bool) *MenuCreate {
	if v != nil {
		_c.SetIsCache(*v)
	}
	return _c
}

// SetIsTab sets the "is_tab" field.
func (_c *MenuCreate) SetIsTab(v bool) *MenuCreate {
	_c.mutation.SetIsTab(v)
	return _c
}

// SetNillableIsTab sets the "is_tab" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsTab(v *bool) *MenuCreate {
	if v != nil {
		_c.SetIsTab(*v)
	}
	return _c
}

// SetIsAffix sets the "is_affix" field.
func (_c *MenuCreate) SetIsAffix(v bool) *MenuCreate {
	_c.mutation.SetIsAffix(v)
	return _c
}

// SetNillableIsAffix sets the "is_affix" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsAffix(v *bool) *MenuCreate {
	if v != nil {
		_c.SetIsAffix(*v)
	}
	return _c
}

// SetFrameSrc sets the "frame_src" field.
func (_c *MenuCreate) SetFrameSrc(v string) *MenuCreate {
	_c.mutation.SetFrameSrc(v)
	return _c
}

// SetNillableFrameSrc sets the "frame_src" field if the given value is not nil.
func (_c *MenuCreate) SetNillableFrameSrc(v *string) *MenuCreate {
	if v != nil {
		_c.SetFrameSrc(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *MenuCreate) SetDescription(v string) *MenuCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MenuCreate) SetNillableDescription(v *string) *MenuCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLink sets the "link" field.
func (_c *MenuCreate) SetLink(v string) *MenuCreate {
	_c.mutation.SetLink(v)
	return _c
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_c *MenuCreate) SetNillableLink(v *string) *MenuCreate {
	if v != nil {
		_c.SetLink(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MenuCreate) SetID(v uint32) *MenuCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParent sets the "parent" edge to the Menu entity.
func (_c *MenuCreate) SetParent(v *Menu) *MenuCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Menu entity by IDs.
func (_c *MenuCreate) AddChildIDs(ids ...uint32) *MenuCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Menu entity.
func (_c *MenuCreate) AddChildren(v ...*Menu) *MenuCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_c *MenuCreate) AddRoleIDs(ids ...uint32) *MenuCreate {
	_c.mutation.AddRoleIDs(ids...)
	return _c
}

// AddRoles adds the "roles" edges to the Role entity.
func (_c *MenuCreate) AddRoles(v ...*Role) *MenuCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoleIDs(ids...)
}

// Mutation returns the MenuMutation object of the builder.
func (_c *MenuCreate) Mutation() *MenuMutation {
	return _c.mutation
}

// Save creates the Menu in the database.
func (_c *MenuCreate) Save(ctx context.Context) (*Menu, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MenuCreate) SaveX(ctx context.Context) *Menu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MenuCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := menu.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := menu.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := menu.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := menu.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.MenuLevel(); !ok {
		v := menu.DefaultMenuLevel
		_c.mutation.SetMenuLevel(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MenuCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Menu.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Menu.updated_at"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "Menu.sort"`)}
	}
	if _, ok := _c.mutation.MenuCode(); !ok {
		return &ValidationError{Name: "menu_code", err: errors.New(`ent: missing required field "Menu.menu_code"`)}
	}
	if v, ok := _c.mutation.MenuCode(); ok {
		if err := menu.MenuCodeValidator(v); err != nil {
			return &ValidationError{Name: "menu_code", err: fmt.Errorf(`ent: validator failed for field "Menu.menu_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MenuName(); !ok {
		return &ValidationError{Name: "menu_name", err: errors.New(`ent: missing required field "Menu.menu_name"`)}
	}
	if v, ok := _c.mutation.MenuName(); ok {
		if err := menu.MenuNameValidator(v); err != nil {
			return &ValidationError{Name: "menu_name", err: fmt.Errorf(`ent: validator failed for field "Menu.menu_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MenuPath(); ok {
		if err := menu.MenuPathValidator(v); err != nil {
			return &ValidationError{Name: "menu_path", err: fmt.Errorf(`ent: validator failed for field "Menu.menu_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Component(); ok {
		if err := menu.ComponentValidator(v); err != nil {
			return &ValidationError{Name: "component", err: fmt.Errorf(`ent: validator failed for field "Menu.component": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Redirect(); ok {
		if err := menu.RedirectValidator(v); err != nil {
			return &ValidationError{Name: "redirect", err: fmt.Errorf(`ent: validator failed for field "Menu.redirect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MenuLevel(); !ok {
		return &ValidationError{Name: "menu_level", err: errors.New(`ent: missing required field "Menu.menu_level"`)}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := menu.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "Menu.icon": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Permission(); ok {
		if err := menu.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "Menu.permission": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ServiceName(); ok {
		if err := menu.ServiceNameValidator(v); err != nil {
			return &ValidationError{Name: "service_name", err: fmt.Errorf(`ent: validator failed for field "Menu.service_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MenuType(); !ok {
		return &ValidationError{Name: "menu_type", err: errors.New(`ent: missing required field "Menu.menu_type"`)}
	}
	if v, ok := _c.mutation.MenuType(); ok {
		if err := menu.MenuTypeValidator(v); err != nil {
			return &ValidationError{Name: "menu_type", err: fmt.Errorf(`ent: validator failed for field "Menu.menu_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FrameSrc(); ok {
		if err := menu.FrameSrcValidator(v); err != nil {
			return &ValidationError{Name: "frame_src", err: fmt.Errorf(`ent: validator failed for field "Menu.frame_src": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Link(); ok {
		if err := menu.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "Menu.link": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := menu.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Menu.id": %w`, err)}
		}
	}
	return nil
}

func (_c *MenuCreate) sqlSave(ctx context.Context) (*Menu, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MenuCreate) createSpec() (*Menu, *sqlgraph.CreateSpec) {
	var (
		_node = &Menu{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(menu.Table, sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(menu.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(menu.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(menu.FieldState, field.TypeBool, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(menu.FieldSort, field.TypeInt32, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.MenuCode(); ok {
		_spec.SetField(menu.FieldMenuCode, field.TypeString, value)
		_node.MenuCode = value
	}
	if value, ok := _c.mutation.MenuName(); ok {
		_spec.SetField(menu.FieldMenuName, field.TypeString, value)
		_node.MenuName = value
	}
	if value, ok := _c.mutation.MenuPath(); ok {
		_spec.SetField(menu.FieldMenuPath, field.TypeString, value)
		_node.MenuPath = &value
	}
	if value, ok := _c.mutation.Component(); ok {
		_spec.SetField(menu.FieldComponent, field.TypeString, value)
		_node.Component = &value
	}
	if value, ok := _c.mutation.Redirect(); ok {
		_spec.SetField(menu.FieldRedirect, field.TypeString, value)
		_node.Redirect = &value
	}
	if value, ok := _c.mutation.MenuLevel(); ok {
		_spec.SetField(menu.FieldMenuLevel, field.TypeUint16, value)
		_node.MenuLevel = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(menu.FieldIcon, field.TypeString, value)
		_node.Icon = &value
	}
	if value, ok := _c.mutation.Permission(); ok {
		_spec.SetField(menu.FieldPermission, field.TypeString, value)
		_node.Permission = &value
	}
	if value, ok := _c.mutation.ServiceName(); ok {
		_spec.SetField(menu.FieldServiceName, field.TypeString, value)
		_node.ServiceName = &value
	}
	if value, ok := _c.mutation.MenuType(); ok {
		_spec.SetField(menu.FieldMenuType, field.TypeString, value)
		_node.MenuType = value
	}
	if value, ok := _c.mutation.IsHidden(); ok {
		_spec.SetField(menu.FieldIsHidden, field.TypeBool, value)
		_node.IsHidden = &value
	}
	if value, ok := _c.mutation.IsBreadcrumb(); ok {
		_spec.SetField(menu.FieldIsBreadcrumb, field.TypeBool, value)
		_node.IsBreadcrumb = &value
	}
	if value, ok := _c.mutation.IsCache(); ok {
		_spec.SetField(menu.FieldIsCache, field.TypeBool, value)
		_node.IsCache = &value
	}
	if value, ok := _c.mutation.IsTab(); ok {
		_spec.SetField(menu.FieldIsTab, field.TypeBool, value)
		_node.IsTab = &value
	}
	if value, ok := _c.mutation.IsAffix(); ok {
		_spec.SetField(menu.FieldIsAffix, field.TypeBool, value)
		_node.IsAffix = &value
	}
	if value, ok := _c.mutation.FrameSrc(); ok {
		_spec.SetField(menu.FieldFrameSrc, field.TypeString, value)
		_node.FrameSrc = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(menu.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Link(); ok {
		_spec.SetField(menu.FieldLink, field.TypeString, value)
		_node.Link = &value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menu.ParentTable,
			Columns: []string{menu.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menu.ChildrenTable,
			Columns: []string{menu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   menu.RolesTable,
			Columns: menu.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MenuCreateBulk is the builder for creating many Menu entities in bulk.
type MenuCreateBulk struct {
	config
	err      error
	builders []*MenuCreate
}

// Save creates the Menu entities in the database.
func (_c *MenuCreateBulk) Save(ctx context.Context) ([]*Menu, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Menu, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MenuCreateBulk) SaveX(ctx context.Context) []*Menu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
