// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wenpiner/last-admin-core/rpc/ent/operationlog"
	"github.com/wenpiner/last-admin-core/rpc/ent/user"
)

// OperationLogCreate is the builder for creating a OperationLog entity.
type OperationLogCreate struct {
	config
	mutation *OperationLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OperationLogCreate) SetCreatedAt(v time.Time) *OperationLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableCreatedAt(v *time.Time) *OperationLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OperationLogCreate) SetUpdatedAt(v time.Time) *OperationLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableUpdatedAt(v *time.Time) *OperationLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OperationLogCreate) SetUserID(v uuid.UUID) *OperationLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableUserID(v *uuid.UUID) *OperationLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *OperationLogCreate) SetUsername(v string) *OperationLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableUsername(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetOperationType sets the "operation_type" field.
func (_c *OperationLogCreate) SetOperationType(v string) *OperationLogCreate {
	_c.mutation.SetOperationType(v)
	return _c
}

// SetModule sets the "module" field.
func (_c *OperationLogCreate) SetModule(v string) *OperationLogCreate {
	_c.mutation.SetModule(v)
	return _c
}

// SetBusinessType sets the "business_type" field.
func (_c *OperationLogCreate) SetBusinessType(v string) *OperationLogCreate {
	_c.mutation.SetBusinessType(v)
	return _c
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableBusinessType(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetBusinessType(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *OperationLogCreate) SetMethod(v string) *OperationLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableMethod(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetRequestURL sets the "request_url" field.
func (_c *OperationLogCreate) SetRequestURL(v string) *OperationLogCreate {
	_c.mutation.SetRequestURL(v)
	return _c
}

// SetNillableRequestURL sets the "request_url" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableRequestURL(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetRequestURL(*v)
	}
	return _c
}

// SetRequestParams sets the "request_params" field.
func (_c *OperationLogCreate) SetRequestParams(v string) *OperationLogCreate {
	_c.mutation.SetRequestParams(v)
	return _c
}

// SetNillableRequestParams sets the "request_params" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableRequestParams(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetRequestParams(*v)
	}
	return _c
}

// SetResponseData sets the "response_data" field.
func (_c *OperationLogCreate) SetResponseData(v string) *OperationLogCreate {
	_c.mutation.SetResponseData(v)
	return _c
}

// SetNillableResponseData sets the "response_data" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableResponseData(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetResponseData(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *OperationLogCreate) SetIPAddress(v string) *OperationLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableIPAddress(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *OperationLogCreate) SetUserAgent(v string) *OperationLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableUserAgent(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *OperationLogCreate) SetLocation(v string) *OperationLogCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableLocation(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetIsSuccess sets the "is_success" field.
func (_c *OperationLogCreate) SetIsSuccess(v bool) *OperationLogCreate {
	_c.mutation.SetIsSuccess(v)
	return _c
}

// SetNillableIsSuccess sets the "is_success" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableIsSuccess(v *bool) *OperationLogCreate {
	if v != nil {
		_c.SetIsSuccess(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *OperationLogCreate) SetErrorMessage(v string) *OperationLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableErrorMessage(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetExecutionTime sets the "execution_time" field.
func (_c *OperationLogCreate) SetExecutionTime(v int) *OperationLogCreate {
	_c.mutation.SetExecutionTime(v)
	return _c
}

// SetNillableExecutionTime sets the "execution_time" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableExecutionTime(v *int) *OperationLogCreate {
	if v != nil {
		_c.SetExecutionTime(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *OperationLogCreate) SetDescription(v string) *OperationLogCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableDescription(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperationLogCreate) SetID(v uint32) *OperationLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OperationLogCreate) SetUser(v *User) *OperationLogCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OperationLogMutation object of the builder.
func (_c *OperationLogCreate) Mutation() *OperationLogMutation {
	return _c.mutation
}

// Save creates the OperationLog in the database.
func (_c *OperationLogCreate) Save(ctx context.Context) (*OperationLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperationLogCreate) SaveX(ctx context.Context) *OperationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OperationLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := operationlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := operationlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsSuccess(); !ok {
		v := operationlog.DefaultIsSuccess
		_c.mutation.SetIsSuccess(v)
	}
	if _, ok := _c.mutation.ExecutionTime(); !ok {
		v := operationlog.DefaultExecutionTime
		_c.mutation.SetExecutionTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperationLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OperationLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OperationLog.updated_at"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := operationlog.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "OperationLog.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OperationType(); !ok {
		return &ValidationError{Name: "operation_type", err: errors.New(`ent: missing required field "OperationLog.operation_type"`)}
	}
	if v, ok := _c.mutation.OperationType(); ok {
		if err := operationlog.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "OperationLog.operation_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "OperationLog.module"`)}
	}
	if v, ok := _c.mutation.Module(); ok {
		if err := operationlog.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "OperationLog.module": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BusinessType(); ok {
		if err := operationlog.BusinessTypeValidator(v); err != nil {
			return &ValidationError{Name: "business_type", err: fmt.Errorf(`ent: validator failed for field "OperationLog.business_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := operationlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OperationLog.method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestURL(); ok {
		if err := operationlog.RequestURLValidator(v); err != nil {
			return &ValidationError{Name: "request_url", err: fmt.Errorf(`ent: validator failed for field "OperationLog.request_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := operationlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "OperationLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := operationlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "OperationLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Location(); ok {
		if err := operationlog.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "OperationLog.location": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSuccess(); !ok {
		return &ValidationError{Name: "is_success", err: errors.New(`ent: missing required field "OperationLog.is_success"`)}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := operationlog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "OperationLog.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionTime(); !ok {
		return &ValidationError{Name: "execution_time", err: errors.New(`ent: missing required field "OperationLog.execution_time"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := operationlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "OperationLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OperationLogCreate) sqlSave(ctx context.Context) (*OperationLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperationLogCreate) createSpec() (*OperationLog, *sqlgraph.CreateSpec) {
	var (
		_node = &OperationLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operationlog.Table, sqlgraph.NewFieldSpec(operationlog.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(operationlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(operationlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(operationlog.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.OperationType(); ok {
		_spec.SetField(operationlog.FieldOperationType, field.TypeString, value)
		_node.OperationType = value
	}
	if value, ok := _c.mutation.Module(); ok {
		_spec.SetField(operationlog.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := _c.mutation.BusinessType(); ok {
		_spec.SetField(operationlog.FieldBusinessType, field.TypeString, value)
		_node.BusinessType = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(operationlog.FieldMethod, field.TypeString, value)
		_node.Method = &value
	}
	if value, ok := _c.mutation.RequestURL(); ok {
		_spec.SetField(operationlog.FieldRequestURL, field.TypeString, value)
		_node.RequestURL = &value
	}
	if value, ok := _c.mutation.RequestParams(); ok {
		_spec.SetField(operationlog.FieldRequestParams, field.TypeString, value)
		_node.RequestParams = &value
	}
	if value, ok := _c.mutation.ResponseData(); ok {
		_spec.SetField(operationlog.FieldResponseData, field.TypeString, value)
		_node.ResponseData = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(operationlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(operationlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(operationlog.FieldLocation, field.TypeString, value)
		_node.Location = &value
	}
	if value, ok := _c.mutation.IsSuccess(); ok {
		_spec.SetField(operationlog.FieldIsSuccess, field.TypeBool, value)
		_node.IsSuccess = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(operationlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.ExecutionTime(); ok {
		_spec.SetField(operationlog.FieldExecutionTime, field.TypeInt, value)
		_node.ExecutionTime = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(operationlog.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   operationlog.UserTable,
			Columns: []string{operationlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OperationLogCreateBulk is the builder for creating many OperationLog entities in bulk.
type OperationLogCreateBulk struct {
	config
	err      error
	builders []*OperationLogCreate
}

// Save creates the OperationLog entities in the database.
func (_c *OperationLogCreateBulk) Save(ctx context.Context) ([]*OperationLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OperationLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperationLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperationLogCreateBulk) SaveX(ctx context.Context) []*OperationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
