// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wenpiner/last-admin-core/rpc/ent/oauthprovider"
	"github.com/wenpiner/last-admin-core/rpc/ent/predicate"
	"github.com/wenpiner/last-admin-core/rpc/ent/user"
	"github.com/wenpiner/last-admin-core/rpc/ent/useroauth"
)

// UserOauthUpdate is the builder for updating UserOauth entities.
type UserOauthUpdate struct {
	config
	hooks    []Hook
	mutation *UserOauthMutation
}

// Where appends a list predicates to the UserOauthUpdate builder.
func (_u *UserOauthUpdate) Where(ps ...predicate.UserOauth) *UserOauthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserOauthUpdate) SetUpdatedAt(v time.Time) *UserOauthUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserOauthUpdate) SetUserID(v uuid.UUID) *UserOauthUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserOauthUpdate) SetNillableUserID(v *uuid.UUID) *UserOauthUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UserOauthUpdate) SetProviderID(v uint32) *UserOauthUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UserOauthUpdate) SetNillableProviderID(v *uint32) *UserOauthUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetOauthID sets the "oauth_id" field.
func (_u *UserOauthUpdate) SetOauthID(v string) *UserOauthUpdate {
	_u.mutation.SetOauthID(v)
	return _u
}

// SetNillableOauthID sets the "oauth_id" field if the given value is not nil.
func (_u *UserOauthUpdate) SetNillableOauthID(v *string) *UserOauthUpdate {
	if v != nil {
		_u.SetOauthID(*v)
	}
	return _u
}

// SetOauthData sets the "oauth_data" field.
func (_u *UserOauthUpdate) SetOauthData(v map[string]interface{}) *UserOauthUpdate {
	_u.mutation.SetOauthData(v)
	return _u
}

// ClearOauthData clears the value of the "oauth_data" field.
func (_u *UserOauthUpdate) ClearOauthData() *UserOauthUpdate {
	_u.mutation.ClearOauthData()
	return _u
}

// SetOauthToken sets the "oauth_token" field.
func (_u *UserOauthUpdate) SetOauthToken(v string) *UserOauthUpdate {
	_u.mutation.SetOauthToken(v)
	return _u
}

// SetNillableOauthToken sets the "oauth_token" field if the given value is not nil.
func (_u *UserOauthUpdate) SetNillableOauthToken(v *string) *UserOauthUpdate {
	if v != nil {
		_u.SetOauthToken(*v)
	}
	return _u
}

// ClearOauthToken clears the value of the "oauth_token" field.
func (_u *UserOauthUpdate) ClearOauthToken() *UserOauthUpdate {
	_u.mutation.ClearOauthToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserOauthUpdate) SetRefreshToken(v string) *UserOauthUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserOauthUpdate) SetNillableRefreshToken(v *string) *UserOauthUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserOauthUpdate) ClearRefreshToken() *UserOauthUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UserOauthUpdate) SetTokenExpiresAt(v time.Time) *UserOauthUpdate {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UserOauthUpdate) SetNillableTokenExpiresAt(v *time.Time) *UserOauthUpdate {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UserOauthUpdate) ClearTokenExpiresAt() *UserOauthUpdate {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserOauthUpdate) SetUser(v *User) *UserOauthUpdate {
	return _u.SetUserID(v.ID)
}

// SetProvider sets the "provider" edge to the OauthProvider entity.
func (_u *UserOauthUpdate) SetProvider(v *OauthProvider) *UserOauthUpdate {
	return _u.SetProviderID(v.ID)
}

// Mutation returns the UserOauthMutation object of the builder.
func (_u *UserOauthUpdate) Mutation() *UserOauthMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserOauthUpdate) ClearUser() *UserOauthUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProvider clears the "provider" edge to the OauthProvider entity.
func (_u *UserOauthUpdate) ClearProvider() *UserOauthUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserOauthUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOauthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserOauthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOauthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserOauthUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useroauth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserOauthUpdate) check() error {
	if v, ok := _u.mutation.OauthID(); ok {
		if err := useroauth.OauthIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_id", err: fmt.Errorf(`ent: validator failed for field "UserOauth.oauth_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOauth.user"`)
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOauth.provider"`)
	}
	return nil
}

func (_u *UserOauthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useroauth.Table, useroauth.Columns, sqlgraph.NewFieldSpec(useroauth.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauth.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OauthID(); ok {
		_spec.SetField(useroauth.FieldOauthID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthData(); ok {
		_spec.SetField(useroauth.FieldOauthData, field.TypeJSON, value)
	}
	if _u.mutation.OauthDataCleared() {
		_spec.ClearField(useroauth.FieldOauthData, field.TypeJSON)
	}
	if value, ok := _u.mutation.OauthToken(); ok {
		_spec.SetField(useroauth.FieldOauthToken, field.TypeString, value)
	}
	if _u.mutation.OauthTokenCleared() {
		_spec.ClearField(useroauth.FieldOauthToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(useroauth.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(useroauth.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(useroauth.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(useroauth.FieldTokenExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.UserTable,
			Columns: []string{useroauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.UserTable,
			Columns: []string{useroauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.ProviderTable,
			Columns: []string{useroauth.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.ProviderTable,
			Columns: []string{useroauth.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserOauthUpdateOne is the builder for updating a single UserOauth entity.
type UserOauthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserOauthMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserOauthUpdateOne) SetUpdatedAt(v time.Time) *UserOauthUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserOauthUpdateOne) SetUserID(v uuid.UUID) *UserOauthUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserOauthUpdateOne) SetNillableUserID(v *uuid.UUID) *UserOauthUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UserOauthUpdateOne) SetProviderID(v uint32) *UserOauthUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UserOauthUpdateOne) SetNillableProviderID(v *uint32) *UserOauthUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetOauthID sets the "oauth_id" field.
func (_u *UserOauthUpdateOne) SetOauthID(v string) *UserOauthUpdateOne {
	_u.mutation.SetOauthID(v)
	return _u
}

// SetNillableOauthID sets the "oauth_id" field if the given value is not nil.
func (_u *UserOauthUpdateOne) SetNillableOauthID(v *string) *UserOauthUpdateOne {
	if v != nil {
		_u.SetOauthID(*v)
	}
	return _u
}

// SetOauthData sets the "oauth_data" field.
func (_u *UserOauthUpdateOne) SetOauthData(v map[string]interface{}) *UserOauthUpdateOne {
	_u.mutation.SetOauthData(v)
	return _u
}

// ClearOauthData clears the value of the "oauth_data" field.
func (_u *UserOauthUpdateOne) ClearOauthData() *UserOauthUpdateOne {
	_u.mutation.ClearOauthData()
	return _u
}

// SetOauthToken sets the "oauth_token" field.
func (_u *UserOauthUpdateOne) SetOauthToken(v string) *UserOauthUpdateOne {
	_u.mutation.SetOauthToken(v)
	return _u
}

// SetNillableOauthToken sets the "oauth_token" field if the given value is not nil.
func (_u *UserOauthUpdateOne) SetNillableOauthToken(v *string) *UserOauthUpdateOne {
	if v != nil {
		_u.SetOauthToken(*v)
	}
	return _u
}

// ClearOauthToken clears the value of the "oauth_token" field.
func (_u *UserOauthUpdateOne) ClearOauthToken() *UserOauthUpdateOne {
	_u.mutation.ClearOauthToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserOauthUpdateOne) SetRefreshToken(v string) *UserOauthUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserOauthUpdateOne) SetNillableRefreshToken(v *string) *UserOauthUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserOauthUpdateOne) ClearRefreshToken() *UserOauthUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UserOauthUpdateOne) SetTokenExpiresAt(v time.Time) *UserOauthUpdateOne {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UserOauthUpdateOne) SetNillableTokenExpiresAt(v *time.Time) *UserOauthUpdateOne {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UserOauthUpdateOne) ClearTokenExpiresAt() *UserOauthUpdateOne {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserOauthUpdateOne) SetUser(v *User) *UserOauthUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProvider sets the "provider" edge to the OauthProvider entity.
func (_u *UserOauthUpdateOne) SetProvider(v *OauthProvider) *UserOauthUpdateOne {
	return _u.SetProviderID(v.ID)
}

// Mutation returns the UserOauthMutation object of the builder.
func (_u *UserOauthUpdateOne) Mutation() *UserOauthMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserOauthUpdateOne) ClearUser() *UserOauthUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProvider clears the "provider" edge to the OauthProvider entity.
func (_u *UserOauthUpdateOne) ClearProvider() *UserOauthUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// Where appends a list predicates to the UserOauthUpdate builder.
func (_u *UserOauthUpdateOne) Where(ps ...predicate.UserOauth) *UserOauthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserOauthUpdateOne) Select(field string, fields ...string) *UserOauthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserOauth entity.
func (_u *UserOauthUpdateOne) Save(ctx context.Context) (*UserOauth, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOauthUpdateOne) SaveX(ctx context.Context) *UserOauth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserOauthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOauthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserOauthUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useroauth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserOauthUpdateOne) check() error {
	if v, ok := _u.mutation.OauthID(); ok {
		if err := useroauth.OauthIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_id", err: fmt.Errorf(`ent: validator failed for field "UserOauth.oauth_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOauth.user"`)
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOauth.provider"`)
	}
	return nil
}

func (_u *UserOauthUpdateOne) sqlSave(ctx context.Context) (_node *UserOauth, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useroauth.Table, useroauth.Columns, sqlgraph.NewFieldSpec(useroauth.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserOauth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroauth.FieldID)
		for _, f := range fields {
			if !useroauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useroauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauth.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OauthID(); ok {
		_spec.SetField(useroauth.FieldOauthID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthData(); ok {
		_spec.SetField(useroauth.FieldOauthData, field.TypeJSON, value)
	}
	if _u.mutation.OauthDataCleared() {
		_spec.ClearField(useroauth.FieldOauthData, field.TypeJSON)
	}
	if value, ok := _u.mutation.OauthToken(); ok {
		_spec.SetField(useroauth.FieldOauthToken, field.TypeString, value)
	}
	if _u.mutation.OauthTokenCleared() {
		_spec.ClearField(useroauth.FieldOauthToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(useroauth.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(useroauth.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(useroauth.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(useroauth.FieldTokenExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.UserTable,
			Columns: []string{useroauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.UserTable,
			Columns: []string{useroauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.ProviderTable,
			Columns: []string{useroauth.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroauth.ProviderTable,
			Columns: []string{useroauth.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserOauth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
