// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wenpiner/last-admin-core/rpc/ent/user"
	"github.com/wenpiner/last-admin-core/rpc/ent/usertotp"
)

// UserTotpCreate is the builder for creating a UserTotp entity.
type UserTotpCreate struct {
	config
	mutation *UserTotpMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserTotpCreate) SetCreatedAt(v time.Time) *UserTotpCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableCreatedAt(v *time.Time) *UserTotpCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserTotpCreate) SetUpdatedAt(v time.Time) *UserTotpCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableUpdatedAt(v *time.Time) *UserTotpCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *UserTotpCreate) SetState(v bool) *UserTotpCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableState(v *bool) *UserTotpCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserTotpCreate) SetUserID(v uuid.UUID) *UserTotpCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSecretKey sets the "secret_key" field.
func (_c *UserTotpCreate) SetSecretKey(v string) *UserTotpCreate {
	_c.mutation.SetSecretKey(v)
	return _c
}

// SetBackupCodes sets the "backup_codes" field.
func (_c *UserTotpCreate) SetBackupCodes(v string) *UserTotpCreate {
	_c.mutation.SetBackupCodes(v)
	return _c
}

// SetNillableBackupCodes sets the "backup_codes" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableBackupCodes(v *string) *UserTotpCreate {
	if v != nil {
		_c.SetBackupCodes(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *UserTotpCreate) SetIsEnabled(v bool) *UserTotpCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableIsEnabled(v *bool) *UserTotpCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetIsVerified sets the "is_verified" field.
func (_c *UserTotpCreate) SetIsVerified(v bool) *UserTotpCreate {
	_c.mutation.SetIsVerified(v)
	return _c
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableIsVerified(v *bool) *UserTotpCreate {
	if v != nil {
		_c.SetIsVerified(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *UserTotpCreate) SetLastUsedAt(v time.Time) *UserTotpCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableLastUsedAt(v *time.Time) *UserTotpCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetLastUsedCode sets the "last_used_code" field.
func (_c *UserTotpCreate) SetLastUsedCode(v string) *UserTotpCreate {
	_c.mutation.SetLastUsedCode(v)
	return _c
}

// SetNillableLastUsedCode sets the "last_used_code" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableLastUsedCode(v *string) *UserTotpCreate {
	if v != nil {
		_c.SetLastUsedCode(*v)
	}
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *UserTotpCreate) SetDeviceName(v string) *UserTotpCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableDeviceName(v *string) *UserTotpCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *UserTotpCreate) SetIssuer(v string) *UserTotpCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableIssuer(v *string) *UserTotpCreate {
	if v != nil {
		_c.SetIssuer(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *UserTotpCreate) SetFailureCount(v int) *UserTotpCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableFailureCount(v *int) *UserTotpCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetLockedUntil sets the "locked_until" field.
func (_c *UserTotpCreate) SetLockedUntil(v time.Time) *UserTotpCreate {
	_c.mutation.SetLockedUntil(v)
	return _c
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_c *UserTotpCreate) SetNillableLockedUntil(v *time.Time) *UserTotpCreate {
	if v != nil {
		_c.SetLockedUntil(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserTotpCreate) SetID(v uint32) *UserTotpCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserTotpCreate) SetUser(v *User) *UserTotpCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserTotpMutation object of the builder.
func (_c *UserTotpCreate) Mutation() *UserTotpMutation {
	return _c.mutation
}

// Save creates the UserTotp in the database.
func (_c *UserTotpCreate) Save(ctx context.Context) (*UserTotp, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserTotpCreate) SaveX(ctx context.Context) *UserTotp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTotpCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTotpCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserTotpCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usertotp.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usertotp.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := usertotp.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := usertotp.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		v := usertotp.DefaultIsVerified
		_c.mutation.SetIsVerified(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := usertotp.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserTotpCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserTotp.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserTotp.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserTotp.user_id"`)}
	}
	if _, ok := _c.mutation.SecretKey(); !ok {
		return &ValidationError{Name: "secret_key", err: errors.New(`ent: missing required field "UserTotp.secret_key"`)}
	}
	if v, ok := _c.mutation.SecretKey(); ok {
		if err := usertotp.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "UserTotp.secret_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BackupCodes(); ok {
		if err := usertotp.BackupCodesValidator(v); err != nil {
			return &ValidationError{Name: "backup_codes", err: fmt.Errorf(`ent: validator failed for field "UserTotp.backup_codes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "UserTotp.is_enabled"`)}
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "UserTotp.is_verified"`)}
	}
	if v, ok := _c.mutation.LastUsedCode(); ok {
		if err := usertotp.LastUsedCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_used_code", err: fmt.Errorf(`ent: validator failed for field "UserTotp.last_used_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := usertotp.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "UserTotp.device_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Issuer(); ok {
		if err := usertotp.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "UserTotp.issuer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "UserTotp.failure_count"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := usertotp.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UserTotp.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserTotp.user"`)}
	}
	return nil
}

func (_c *UserTotpCreate) sqlSave(ctx context.Context) (*UserTotp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserTotpCreate) createSpec() (*UserTotp, *sqlgraph.CreateSpec) {
	var (
		_node = &UserTotp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usertotp.Table, sqlgraph.NewFieldSpec(usertotp.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usertotp.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usertotp.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(usertotp.FieldState, field.TypeBool, value)
		_node.State = value
	}
	if value, ok := _c.mutation.SecretKey(); ok {
		_spec.SetField(usertotp.FieldSecretKey, field.TypeString, value)
		_node.SecretKey = value
	}
	if value, ok := _c.mutation.BackupCodes(); ok {
		_spec.SetField(usertotp.FieldBackupCodes, field.TypeString, value)
		_node.BackupCodes = &value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(usertotp.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if value, ok := _c.mutation.IsVerified(); ok {
		_spec.SetField(usertotp.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(usertotp.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.LastUsedCode(); ok {
		_spec.SetField(usertotp.FieldLastUsedCode, field.TypeString, value)
		_node.LastUsedCode = &value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(usertotp.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = &value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(usertotp.FieldIssuer, field.TypeString, value)
		_node.Issuer = &value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(usertotp.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.LockedUntil(); ok {
		_spec.SetField(usertotp.FieldLockedUntil, field.TypeTime, value)
		_node.LockedUntil = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertotp.UserTable,
			Columns: []string{usertotp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserTotpCreateBulk is the builder for creating many UserTotp entities in bulk.
type UserTotpCreateBulk struct {
	config
	err      error
	builders []*UserTotpCreate
}

// Save creates the UserTotp entities in the database.
func (_c *UserTotpCreateBulk) Save(ctx context.Context) ([]*UserTotp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserTotp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserTotpMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserTotpCreateBulk) SaveX(ctx context.Context) []*UserTotp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTotpCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTotpCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
