Name: core.api
Host: 0.0.0.0
Port: ${SERVER_PORT}

# 认证配置
Auth:
  AccessSecret: ${AUTH_ACCESS_SECRET}
  AccessExpire: ${AUTH_ACCESS_EXPIRE}

I18nConf:
  Dir: ""

# 项目配置
ProjectConf:
  RegisterRoleValue: "super" # 注册用户默认角色

# 验证码配置
CaptchaConf:
  # 验证码类型: digit(数字), string(字符串), math(数学), chinese(中文), audio(音频), random(随机)
  Type: random

  # 数字验证码配置
  Digit:
    Height: 80
    Width: 240
    Length: 5
    MaxSkew: 0.7
    DotCount: 80

  # 字符串验证码配置
  String:
    Height: 60
    Width: 240
    NoiseCount: 0
    ShowLineOptions: 0
    Length: 4
    Source: "1234567890qwertyuioplkjhgfdsazxcvbnm"
    BgColor:
      R: 254
      G: 254
      B: 254
      A: 254
    Fonts:
      - "wqy-microhei.ttc"
      - "3Dumb.ttf"
      - "ApothecaryFont.ttf"
      - "Comismsh.ttf"
      - "DENNEthree-dee.ttf"
      - "DeborahFancyDress.ttf"
      - "Flim-Flam.ttf"
      - "RitaSmith.ttf"
      - "actionj.ttf"
      - "chromohv.ttf"

  # 数学验证码配置
  Math:
    Height: 60
    Width: 240
    NoiseCount: 0
    ShowLineOptions: 0
    BgColor:
      R: 254
      G: 254
      B: 254
      A: 254
    Fonts:
      - "wqy-microhei.ttc"
      - "3Dumb.ttf"
      - "ApothecaryFont.ttf"
      - "Comismsh.ttf"
      - "DENNEthree-dee.ttf"
      - "DeborahFancyDress.ttf"
      - "Flim-Flam.ttf"
      - "RitaSmith.ttf"
      - "actionj.ttf"
      - "chromohv.ttf"

  # 中文验证码配置
  Chinese:
    Height: 60
    Width: 240
    NoiseCount: 0
    ShowLineOptions: 0
    Length: 3
    Source: "设想你在处理消费者的音频输出音频可能无论什么都没有任何输出或者它可能是单声道立体声或是环绕立体声的假设我们需要不同类型的音频输出来处理不同的情况的一是了不在人有我他这个们中来上大为和国同地道时动之也子出而要于就下得可你说生年着进事成日只系知家自设后新现前所与及相关意点育业文反政作面方内法当事最代想数电此理定行本高第现表二者或快手但全利平真明看原又公被度情信金实四三力问等五发员已部己无使重前西声外格化代战口指用提十美表教然命结见指或水今位目加流如制量还必结特革并指总办保组条计车几管期市量联五七八九干百千万亿见元角分秒时天周月季年今明昨前花草树木东西南北中外内上下左右前后远近高低长短大小多少冷热轻重快慢强弱光明真假美丑善恶喜怒哀乐爱恨情仇恩怨生死存亡成败兴衰荣辱福祸吉凶风雪山川湖海天电风雨雷电金木水火土春夏秋冬爸妈爷奶奶兄弟姐妹叔伯姑舅姨夫妻子儿女你我他她它我们你们他们她们它们身手头脸眼耳鼻口牙舌心肝脾肺肾骨肉血皮毛衣食住行吃喝拉撒睡走跑跳飞游爬滚打字词句章篇书笔纸墨砚琴棋书画诗词歌赋梅兰竹菊松柏桃李柳杨桌椅床柜门窗墙地砖瓦房舍庭院楼台亭阁京沪津渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼"
    BgColor:
      R: 254
      G: 254
      B: 254
      A: 254
    Fonts:
      - "wqy-microhei.ttc"

  # 音频验证码配置
  Audio:
    Length: 4
    Language: "zh"

  # 随机验证码配置
  Random:
    # 启用的验证码类型
    EnabledTypes:
      - "digit"
      - "string"
      - "math"
      - "chinese"
    # 是否排除音频验证码
    ExcludeAudio: true

  # 存储配置
  Store:
    # 存储类型: memory(内存), redis(Redis)
    Type: redis
    # 过期时间 (分钟)
    Expire: "5m"
    # Key前缀
    KeyPrefix: "captcha:"
    # Redis配置
    Redis:
      Addr: "127.0.0.1:16379"
      Password: "redis123"
      DB: 0
      PoolSize: 10

# Redis配置
RedisConf:
  Host: "127.0.0.1:16379"
  Password: "redis123"
  DB: 0
  PoolSize: 10

# Rpc 服务
CoreRpc:
  Target: "127.0.0.1:8080"

# Casbin数据库配置
CasbinDatabaseConf:
  Host: "127.0.0.1"
  Port: 5432
  Username: "postgres"
  Password: "postgres"
  DatabaseName: "last_admin"
  SSLMode: "disable"
  DBType: "postgres"
  MaxOpenConns: 100
  MaxIdleConns: 10
  CacheTime: 300
  DBPath: ""
