// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// API is the predicate function for api builders.
type API func(*sql.Selector)

// Configuration is the predicate function for configuration builders.
type Configuration func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// DictItem is the predicate function for dictitem builders.
type DictItem func(*sql.Selector)

// DictType is the predicate function for dicttype builders.
type DictType func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// OauthProvider is the predicate function for oauthprovider builders.
type OauthProvider func(*sql.Selector)

// OperationLog is the predicate function for operationlog builders.
type OperationLog func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserTotp is the predicate function for usertotp builders.
type UserTotp func(*sql.Selector)
