// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package server

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/internal/logic/operationlogservice"
	"github.com/wenpiner/last-admin-core/rpc/internal/svc"
	"github.com/wenpiner/last-admin-core/rpc/types/core"
)

type OperationLogServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedOperationLogServiceServer
}

func NewOperationLogServiceServer(svcCtx *svc.ServiceContext) *OperationLogServiceServer {
	return &OperationLogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OperationLogServiceServer) CreateOperationLog(ctx context.Context, in *core.OperationLogInfo) (*core.BaseResponse, error) {
	l := operationlogservicelogic.NewCreateOperationLogLogic(ctx, s.svcCtx)
	return l.CreateOperationLog(in)
}

func (s *OperationLogServiceServer) ListOperationLog(ctx context.Context, in *core.OperationLogListRequest) (*core.OperationLogListResponse, error) {
	l := operationlogservicelogic.NewListOperationLogLogic(ctx, s.svcCtx)
	return l.ListOperationLog(in)
}
