// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: core.proto

package menuservice

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/types/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApiInfo                    = core.ApiInfo
	ApiListRequest             = core.ApiListRequest
	ApiListResponse            = core.ApiListResponse
	BackupCodesResponse        = core.BackupCodesResponse
	BasePageRequest            = core.BasePageRequest
	BasePageResp               = core.BasePageResp
	BaseResponse               = core.BaseResponse
	CleanExpiredTokensRequest  = core.CleanExpiredTokensRequest
	CleanExpiredTokensResponse = core.CleanExpiredTokensResponse
	CreateTokenRequest         = core.CreateTokenRequest
	DepartmentInfo             = core.DepartmentInfo
	DepartmentListRequest      = core.DepartmentListRequest
	DepartmentListResponse     = core.DepartmentListResponse
	DictInfo                   = core.DictInfo
	DictItemInfo               = core.DictItemInfo
	DictItemListRequest        = core.DictItemListRequest
	DictItemListResponse       = core.DictItemListResponse
	DictListRequest            = core.DictListRequest
	DictListResponse           = core.DictListResponse
	DisableTotpRequest         = core.DisableTotpRequest
	EmptyRequest               = core.EmptyRequest
	EnableTotpRequest          = core.EnableTotpRequest
	ID32Request                = core.ID32Request
	ID32SRequest               = core.ID32SRequest
	IDRequest                  = core.IDRequest
	IDSRequest                 = core.IDSRequest
	MenuInfo                   = core.MenuInfo
	MenuListRequest            = core.MenuListRequest
	MenuListResponse           = core.MenuListResponse
	MenuMeta                   = core.MenuMeta
	OauthCallbackRequest       = core.OauthCallbackRequest
	OauthLoginRequest          = core.OauthLoginRequest
	OauthProviderInfo          = core.OauthProviderInfo
	OauthProviderListRequest   = core.OauthProviderListRequest
	OauthProviderListResponse  = core.OauthProviderListResponse
	OauthRedirectResponse      = core.OauthRedirectResponse
	PositionInfo               = core.PositionInfo
	PositionListRequest        = core.PositionListRequest
	PositionListResponse       = core.PositionListResponse
	RoleApiListResponse        = core.RoleApiListResponse
	RoleApiRequest             = core.RoleApiRequest
	RoleInfo                   = core.RoleInfo
	RoleListRequest            = core.RoleListRequest
	RoleListResponse           = core.RoleListResponse
	RoleMenuListResponse       = core.RoleMenuListResponse
	RoleMenuRequest            = core.RoleMenuRequest
	StringListResponse         = core.StringListResponse
	StringRequest              = core.StringRequest
	TokenInfo                  = core.TokenInfo
	TokenListRequest           = core.TokenListRequest
	TokenListResponse          = core.TokenListResponse
	TotpInfo                   = core.TotpInfo
	TotpSetupConfirmResponse   = core.TotpSetupConfirmResponse
	TotpSetupResponse          = core.TotpSetupResponse
	TotpStatusResponse         = core.TotpStatusResponse
	UUIDRequest                = core.UUIDRequest
	UUIDSRequest               = core.UUIDSRequest
	UpdateTokenLastUsedRequest = core.UpdateTokenLastUsedRequest
	UseBackupCodeRequest       = core.UseBackupCodeRequest
	UserInfo                   = core.UserInfo
	UserListRequest            = core.UserListRequest
	UserListResponse           = core.UserListResponse
	VerifyTotpCodeRequest      = core.VerifyTotpCodeRequest
	VerifyTotpCodeResponse     = core.VerifyTotpCodeResponse
	VerifyTotpSetupRequest     = core.VerifyTotpSetupRequest

	MenuService interface {
		// 创建或更新菜单
		CreateOrUpdateMenu(ctx context.Context, in *MenuInfo, opts ...grpc.CallOption) (*MenuInfo, error)
		// 删除菜单
		DeleteMenu(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*BaseResponse, error)
		// 获取菜单
		GetMenu(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*MenuInfo, error)
		// 获取菜单列表
		ListMenu(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuListResponse, error)
		// 通过角色查询菜单
		ListMenuByRole(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*MenuListResponse, error)
		// 获取角色对应的所有页面权限
		ListPagePermissionByRole(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringListResponse, error)
	}

	defaultMenuService struct {
		cli zrpc.Client
	}
)

func NewMenuService(cli zrpc.Client) MenuService {
	return &defaultMenuService{
		cli: cli,
	}
}

// 创建或更新菜单
func (m *defaultMenuService) CreateOrUpdateMenu(ctx context.Context, in *MenuInfo, opts ...grpc.CallOption) (*MenuInfo, error) {
	client := core.NewMenuServiceClient(m.cli.Conn())
	return client.CreateOrUpdateMenu(ctx, in, opts...)
}

// 删除菜单
func (m *defaultMenuService) DeleteMenu(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := core.NewMenuServiceClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

// 获取菜单
func (m *defaultMenuService) GetMenu(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*MenuInfo, error) {
	client := core.NewMenuServiceClient(m.cli.Conn())
	return client.GetMenu(ctx, in, opts...)
}

// 获取菜单列表
func (m *defaultMenuService) ListMenu(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuListResponse, error) {
	client := core.NewMenuServiceClient(m.cli.Conn())
	return client.ListMenu(ctx, in, opts...)
}

// 通过角色查询菜单
func (m *defaultMenuService) ListMenuByRole(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*MenuListResponse, error) {
	client := core.NewMenuServiceClient(m.cli.Conn())
	return client.ListMenuByRole(ctx, in, opts...)
}

// 获取角色对应的所有页面权限
func (m *defaultMenuService) ListPagePermissionByRole(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringListResponse, error) {
	client := core.NewMenuServiceClient(m.cli.Conn())
	return client.ListPagePermissionByRole(ctx, in, opts...)
}
