// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: core.proto

package server

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/internal/logic/userservice"
	"github.com/wenpiner/last-admin-core/rpc/internal/svc"
	"github.com/wenpiner/last-admin-core/rpc/types/core"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建用户
func (s *UserServiceServer) CreateUser(ctx context.Context, in *core.UserInfo) (*core.UserInfo, error) {
	l := userservicelogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

// 更新用户
func (s *UserServiceServer) UpdateUser(ctx context.Context, in *core.UserInfo) (*core.UserInfo, error) {
	l := userservicelogic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

// 删除用户
func (s *UserServiceServer) DeleteUser(ctx context.Context, in *core.UUIDRequest) (*core.BaseResponse, error) {
	l := userservicelogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

// 获取用户
func (s *UserServiceServer) GetUser(ctx context.Context, in *core.UUIDRequest) (*core.UserInfo, error) {
	l := userservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 获取用户列表
func (s *UserServiceServer) ListUser(ctx context.Context, in *core.UserListRequest) (*core.UserListResponse, error) {
	l := userservicelogic.NewListUserLogic(ctx, s.svcCtx)
	return l.ListUser(in)
}

// 获取用户 - 用户用户名
func (s *UserServiceServer) GetUserByUsername(ctx context.Context, in *core.StringRequest) (*core.UserInfo, error) {
	l := userservicelogic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}

// TOTP相关接口
func (s *UserServiceServer) EnableTotp(ctx context.Context, in *core.EnableTotpRequest) (*core.TotpSetupResponse, error) {
	l := userservicelogic.NewEnableTotpLogic(ctx, s.svcCtx)
	return l.EnableTotp(in)
}

// 验证并确认TOTP设置
func (s *UserServiceServer) VerifyTotpSetup(ctx context.Context, in *core.VerifyTotpSetupRequest) (*core.TotpSetupConfirmResponse, error) {
	l := userservicelogic.NewVerifyTotpSetupLogic(ctx, s.svcCtx)
	return l.VerifyTotpSetup(in)
}

// 禁用TOTP
func (s *UserServiceServer) DisableTotp(ctx context.Context, in *core.DisableTotpRequest) (*core.BaseResponse, error) {
	l := userservicelogic.NewDisableTotpLogic(ctx, s.svcCtx)
	return l.DisableTotp(in)
}

// 验证TOTP代码（用于登录）
func (s *UserServiceServer) VerifyTotpCode(ctx context.Context, in *core.VerifyTotpCodeRequest) (*core.VerifyTotpCodeResponse, error) {
	l := userservicelogic.NewVerifyTotpCodeLogic(ctx, s.svcCtx)
	return l.VerifyTotpCode(in)
}

// 获取用户TOTP状态
func (s *UserServiceServer) GetTotpStatus(ctx context.Context, in *core.UUIDRequest) (*core.TotpStatusResponse, error) {
	l := userservicelogic.NewGetTotpStatusLogic(ctx, s.svcCtx)
	return l.GetTotpStatus(in)
}

// 重新生成备用恢复码
func (s *UserServiceServer) RegenerateBackupCodes(ctx context.Context, in *core.UUIDRequest) (*core.BackupCodesResponse, error) {
	l := userservicelogic.NewRegenerateBackupCodesLogic(ctx, s.svcCtx)
	return l.RegenerateBackupCodes(in)
}

// 使用备用恢复码
func (s *UserServiceServer) UseBackupCode(ctx context.Context, in *core.UseBackupCodeRequest) (*core.BaseResponse, error) {
	l := userservicelogic.NewUseBackupCodeLogic(ctx, s.svcCtx)
	return l.UseBackupCode(in)
}
