// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: core.proto

package server

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/internal/logic/configurationservice"
	"github.com/wenpiner/last-admin-core/rpc/internal/svc"
	"github.com/wenpiner/last-admin-core/rpc/types/core"
)

type ConfigurationServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedConfigurationServiceServer
}

func NewConfigurationServiceServer(svcCtx *svc.ServiceContext) *ConfigurationServiceServer {
	return &ConfigurationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ConfigurationServiceServer) GetConfiguration(ctx context.Context, in *core.StringRequest) (*core.ConfigurationInfo, error) {
	l := configurationservicelogic.NewGetConfigurationLogic(ctx, s.svcCtx)
	return l.GetConfiguration(in)
}

func (s *ConfigurationServiceServer) ListConfiguration(ctx context.Context, in *core.ConfigurationListRequest) (*core.ConfigurationListResponse, error) {
	l := configurationservicelogic.NewListConfigurationLogic(ctx, s.svcCtx)
	return l.ListConfiguration(in)
}

func (s *ConfigurationServiceServer) CreateOrUpdateConfiguration(ctx context.Context, in *core.ConfigurationInfo) (*core.ConfigurationInfo, error) {
	l := configurationservicelogic.NewCreateOrUpdateConfigurationLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateConfiguration(in)
}

func (s *ConfigurationServiceServer) DeleteConfiguration(ctx context.Context, in *core.StringRequest) (*core.BaseResponse, error) {
	l := configurationservicelogic.NewDeleteConfigurationLogic(ctx, s.svcCtx)
	return l.DeleteConfiguration(in)
}

// 验证某个配置的值是否有效
func (s *ConfigurationServiceServer) ValidateConfiguration(ctx context.Context, in *core.ValidateConfigurationRequest) (*core.ValidateConfigurationResponse, error) {
	l := configurationservicelogic.NewValidateConfigurationLogic(ctx, s.svcCtx)
	return l.ValidateConfiguration(in)
}
