// Code generated by ent, DO NOT EDIT.

package oauthprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthprovider type in the database.
	Label = "oauth_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldProviderName holds the string denoting the provider_name field in the database.
	FieldProviderName = "provider_name"
	// FieldProviderCode holds the string denoting the provider_code field in the database.
	FieldProviderCode = "provider_code"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldClientSecret holds the string denoting the client_secret field in the database.
	FieldClientSecret = "client_secret"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldAuthorizationURL holds the string denoting the authorization_url field in the database.
	FieldAuthorizationURL = "authorization_url"
	// FieldTokenURL holds the string denoting the token_url field in the database.
	FieldTokenURL = "token_url"
	// FieldUserinfoURL holds the string denoting the userinfo_url field in the database.
	FieldUserinfoURL = "userinfo_url"
	// FieldLogoutURL holds the string denoting the logout_url field in the database.
	FieldLogoutURL = "logout_url"
	// FieldAuthStyle holds the string denoting the auth_style field in the database.
	FieldAuthStyle = "auth_style"
	// EdgeTokens holds the string denoting the tokens edge name in mutations.
	EdgeTokens = "tokens"
	// Table holds the table name of the oauthprovider in the database.
	Table = "sys_oauth_providers"
	// TokensTable is the table that holds the tokens relation/edge.
	TokensTable = "sys_tokens"
	// TokensInverseTable is the table name for the Token entity.
	// It exists in this package in order to avoid circular dependency with the "token" package.
	TokensInverseTable = "sys_tokens"
	// TokensColumn is the table column denoting the tokens relation/edge.
	TokensColumn = "provider_id"
)

// Columns holds all SQL columns for oauthprovider fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldState,
	FieldProviderName,
	FieldProviderCode,
	FieldClientID,
	FieldClientSecret,
	FieldRedirectURI,
	FieldScopes,
	FieldAuthorizationURL,
	FieldTokenURL,
	FieldUserinfoURL,
	FieldLogoutURL,
	FieldAuthStyle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState bool
	// ProviderNameValidator is a validator for the "provider_name" field. It is called by the builders before save.
	ProviderNameValidator func(string) error
	// ProviderCodeValidator is a validator for the "provider_code" field. It is called by the builders before save.
	ProviderCodeValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// ClientSecretValidator is a validator for the "client_secret" field. It is called by the builders before save.
	ClientSecretValidator func(string) error
	// RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	RedirectURIValidator func(string) error
	// ScopesValidator is a validator for the "scopes" field. It is called by the builders before save.
	ScopesValidator func(string) error
	// AuthorizationURLValidator is a validator for the "authorization_url" field. It is called by the builders before save.
	AuthorizationURLValidator func(string) error
	// TokenURLValidator is a validator for the "token_url" field. It is called by the builders before save.
	TokenURLValidator func(string) error
	// UserinfoURLValidator is a validator for the "userinfo_url" field. It is called by the builders before save.
	UserinfoURLValidator func(string) error
	// LogoutURLValidator is a validator for the "logout_url" field. It is called by the builders before save.
	LogoutURLValidator func(string) error
	// DefaultAuthStyle holds the default value on creation for the "auth_style" field.
	DefaultAuthStyle uint8
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the OauthProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByProviderName orders the results by the provider_name field.
func ByProviderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderName, opts...).ToFunc()
}

// ByProviderCode orders the results by the provider_code field.
func ByProviderCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderCode, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByClientSecret orders the results by the client_secret field.
func ByClientSecret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientSecret, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByScopes orders the results by the scopes field.
func ByScopes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopes, opts...).ToFunc()
}

// ByAuthorizationURL orders the results by the authorization_url field.
func ByAuthorizationURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizationURL, opts...).ToFunc()
}

// ByTokenURL orders the results by the token_url field.
func ByTokenURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenURL, opts...).ToFunc()
}

// ByUserinfoURL orders the results by the userinfo_url field.
func ByUserinfoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserinfoURL, opts...).ToFunc()
}

// ByLogoutURL orders the results by the logout_url field.
func ByLogoutURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoutURL, opts...).ToFunc()
}

// ByAuthStyle orders the results by the auth_style field.
func ByAuthStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthStyle, opts...).ToFunc()
}

// ByTokensCount orders the results by tokens count.
func ByTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTokensStep(), opts...)
	}
}

// ByTokens orders the results by tokens terms.
func ByTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TokensTable, TokensColumn),
	)
}
