// Code generated by ent, DO NOT EDIT.

package oauthprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/wenpiner/last-admin-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v bool) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldState, v))
}

// ProviderName applies equality check predicate on the "provider_name" field. It's identical to ProviderNameEQ.
func ProviderName(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldProviderName, v))
}

// ProviderCode applies equality check predicate on the "provider_code" field. It's identical to ProviderCodeEQ.
func ProviderCode(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldProviderCode, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldClientID, v))
}

// ClientSecret applies equality check predicate on the "client_secret" field. It's identical to ClientSecretEQ.
func ClientSecret(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldClientSecret, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldRedirectURI, v))
}

// Scopes applies equality check predicate on the "scopes" field. It's identical to ScopesEQ.
func Scopes(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldScopes, v))
}

// AuthorizationURL applies equality check predicate on the "authorization_url" field. It's identical to AuthorizationURLEQ.
func AuthorizationURL(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldAuthorizationURL, v))
}

// TokenURL applies equality check predicate on the "token_url" field. It's identical to TokenURLEQ.
func TokenURL(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldTokenURL, v))
}

// UserinfoURL applies equality check predicate on the "userinfo_url" field. It's identical to UserinfoURLEQ.
func UserinfoURL(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldUserinfoURL, v))
}

// LogoutURL applies equality check predicate on the "logout_url" field. It's identical to LogoutURLEQ.
func LogoutURL(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldLogoutURL, v))
}

// AuthStyle applies equality check predicate on the "auth_style" field. It's identical to AuthStyleEQ.
func AuthStyle(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldAuthStyle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v bool) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v bool) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotNull(FieldState))
}

// ProviderNameEQ applies the EQ predicate on the "provider_name" field.
func ProviderNameEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldProviderName, v))
}

// ProviderNameNEQ applies the NEQ predicate on the "provider_name" field.
func ProviderNameNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldProviderName, v))
}

// ProviderNameIn applies the In predicate on the "provider_name" field.
func ProviderNameIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldProviderName, vs...))
}

// ProviderNameNotIn applies the NotIn predicate on the "provider_name" field.
func ProviderNameNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldProviderName, vs...))
}

// ProviderNameGT applies the GT predicate on the "provider_name" field.
func ProviderNameGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldProviderName, v))
}

// ProviderNameGTE applies the GTE predicate on the "provider_name" field.
func ProviderNameGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldProviderName, v))
}

// ProviderNameLT applies the LT predicate on the "provider_name" field.
func ProviderNameLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldProviderName, v))
}

// ProviderNameLTE applies the LTE predicate on the "provider_name" field.
func ProviderNameLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldProviderName, v))
}

// ProviderNameContains applies the Contains predicate on the "provider_name" field.
func ProviderNameContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldProviderName, v))
}

// ProviderNameHasPrefix applies the HasPrefix predicate on the "provider_name" field.
func ProviderNameHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldProviderName, v))
}

// ProviderNameHasSuffix applies the HasSuffix predicate on the "provider_name" field.
func ProviderNameHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldProviderName, v))
}

// ProviderNameEqualFold applies the EqualFold predicate on the "provider_name" field.
func ProviderNameEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldProviderName, v))
}

// ProviderNameContainsFold applies the ContainsFold predicate on the "provider_name" field.
func ProviderNameContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldProviderName, v))
}

// ProviderCodeEQ applies the EQ predicate on the "provider_code" field.
func ProviderCodeEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldProviderCode, v))
}

// ProviderCodeNEQ applies the NEQ predicate on the "provider_code" field.
func ProviderCodeNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldProviderCode, v))
}

// ProviderCodeIn applies the In predicate on the "provider_code" field.
func ProviderCodeIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldProviderCode, vs...))
}

// ProviderCodeNotIn applies the NotIn predicate on the "provider_code" field.
func ProviderCodeNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldProviderCode, vs...))
}

// ProviderCodeGT applies the GT predicate on the "provider_code" field.
func ProviderCodeGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldProviderCode, v))
}

// ProviderCodeGTE applies the GTE predicate on the "provider_code" field.
func ProviderCodeGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldProviderCode, v))
}

// ProviderCodeLT applies the LT predicate on the "provider_code" field.
func ProviderCodeLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldProviderCode, v))
}

// ProviderCodeLTE applies the LTE predicate on the "provider_code" field.
func ProviderCodeLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldProviderCode, v))
}

// ProviderCodeContains applies the Contains predicate on the "provider_code" field.
func ProviderCodeContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldProviderCode, v))
}

// ProviderCodeHasPrefix applies the HasPrefix predicate on the "provider_code" field.
func ProviderCodeHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldProviderCode, v))
}

// ProviderCodeHasSuffix applies the HasSuffix predicate on the "provider_code" field.
func ProviderCodeHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldProviderCode, v))
}

// ProviderCodeEqualFold applies the EqualFold predicate on the "provider_code" field.
func ProviderCodeEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldProviderCode, v))
}

// ProviderCodeContainsFold applies the ContainsFold predicate on the "provider_code" field.
func ProviderCodeContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldProviderCode, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretEQ applies the EQ predicate on the "client_secret" field.
func ClientSecretEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldClientSecret, v))
}

// ClientSecretNEQ applies the NEQ predicate on the "client_secret" field.
func ClientSecretNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldClientSecret, v))
}

// ClientSecretIn applies the In predicate on the "client_secret" field.
func ClientSecretIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldClientSecret, vs...))
}

// ClientSecretNotIn applies the NotIn predicate on the "client_secret" field.
func ClientSecretNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldClientSecret, vs...))
}

// ClientSecretGT applies the GT predicate on the "client_secret" field.
func ClientSecretGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldClientSecret, v))
}

// ClientSecretGTE applies the GTE predicate on the "client_secret" field.
func ClientSecretGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldClientSecret, v))
}

// ClientSecretLT applies the LT predicate on the "client_secret" field.
func ClientSecretLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldClientSecret, v))
}

// ClientSecretLTE applies the LTE predicate on the "client_secret" field.
func ClientSecretLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldClientSecret, v))
}

// ClientSecretContains applies the Contains predicate on the "client_secret" field.
func ClientSecretContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldClientSecret, v))
}

// ClientSecretHasPrefix applies the HasPrefix predicate on the "client_secret" field.
func ClientSecretHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldClientSecret, v))
}

// ClientSecretHasSuffix applies the HasSuffix predicate on the "client_secret" field.
func ClientSecretHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldClientSecret, v))
}

// ClientSecretEqualFold applies the EqualFold predicate on the "client_secret" field.
func ClientSecretEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldClientSecret, v))
}

// ClientSecretContainsFold applies the ContainsFold predicate on the "client_secret" field.
func ClientSecretContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldClientSecret, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldRedirectURI, v))
}

// ScopesEQ applies the EQ predicate on the "scopes" field.
func ScopesEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldScopes, v))
}

// ScopesNEQ applies the NEQ predicate on the "scopes" field.
func ScopesNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldScopes, v))
}

// ScopesIn applies the In predicate on the "scopes" field.
func ScopesIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldScopes, vs...))
}

// ScopesNotIn applies the NotIn predicate on the "scopes" field.
func ScopesNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldScopes, vs...))
}

// ScopesGT applies the GT predicate on the "scopes" field.
func ScopesGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldScopes, v))
}

// ScopesGTE applies the GTE predicate on the "scopes" field.
func ScopesGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldScopes, v))
}

// ScopesLT applies the LT predicate on the "scopes" field.
func ScopesLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldScopes, v))
}

// ScopesLTE applies the LTE predicate on the "scopes" field.
func ScopesLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldScopes, v))
}

// ScopesContains applies the Contains predicate on the "scopes" field.
func ScopesContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldScopes, v))
}

// ScopesHasPrefix applies the HasPrefix predicate on the "scopes" field.
func ScopesHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldScopes, v))
}

// ScopesHasSuffix applies the HasSuffix predicate on the "scopes" field.
func ScopesHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldScopes, v))
}

// ScopesIsNil applies the IsNil predicate on the "scopes" field.
func ScopesIsNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIsNull(FieldScopes))
}

// ScopesNotNil applies the NotNil predicate on the "scopes" field.
func ScopesNotNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotNull(FieldScopes))
}

// ScopesEqualFold applies the EqualFold predicate on the "scopes" field.
func ScopesEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldScopes, v))
}

// ScopesContainsFold applies the ContainsFold predicate on the "scopes" field.
func ScopesContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldScopes, v))
}

// AuthorizationURLEQ applies the EQ predicate on the "authorization_url" field.
func AuthorizationURLEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldAuthorizationURL, v))
}

// AuthorizationURLNEQ applies the NEQ predicate on the "authorization_url" field.
func AuthorizationURLNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldAuthorizationURL, v))
}

// AuthorizationURLIn applies the In predicate on the "authorization_url" field.
func AuthorizationURLIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldAuthorizationURL, vs...))
}

// AuthorizationURLNotIn applies the NotIn predicate on the "authorization_url" field.
func AuthorizationURLNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldAuthorizationURL, vs...))
}

// AuthorizationURLGT applies the GT predicate on the "authorization_url" field.
func AuthorizationURLGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldAuthorizationURL, v))
}

// AuthorizationURLGTE applies the GTE predicate on the "authorization_url" field.
func AuthorizationURLGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldAuthorizationURL, v))
}

// AuthorizationURLLT applies the LT predicate on the "authorization_url" field.
func AuthorizationURLLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldAuthorizationURL, v))
}

// AuthorizationURLLTE applies the LTE predicate on the "authorization_url" field.
func AuthorizationURLLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldAuthorizationURL, v))
}

// AuthorizationURLContains applies the Contains predicate on the "authorization_url" field.
func AuthorizationURLContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldAuthorizationURL, v))
}

// AuthorizationURLHasPrefix applies the HasPrefix predicate on the "authorization_url" field.
func AuthorizationURLHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldAuthorizationURL, v))
}

// AuthorizationURLHasSuffix applies the HasSuffix predicate on the "authorization_url" field.
func AuthorizationURLHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldAuthorizationURL, v))
}

// AuthorizationURLEqualFold applies the EqualFold predicate on the "authorization_url" field.
func AuthorizationURLEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldAuthorizationURL, v))
}

// AuthorizationURLContainsFold applies the ContainsFold predicate on the "authorization_url" field.
func AuthorizationURLContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldAuthorizationURL, v))
}

// TokenURLEQ applies the EQ predicate on the "token_url" field.
func TokenURLEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldTokenURL, v))
}

// TokenURLNEQ applies the NEQ predicate on the "token_url" field.
func TokenURLNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldTokenURL, v))
}

// TokenURLIn applies the In predicate on the "token_url" field.
func TokenURLIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldTokenURL, vs...))
}

// TokenURLNotIn applies the NotIn predicate on the "token_url" field.
func TokenURLNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldTokenURL, vs...))
}

// TokenURLGT applies the GT predicate on the "token_url" field.
func TokenURLGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldTokenURL, v))
}

// TokenURLGTE applies the GTE predicate on the "token_url" field.
func TokenURLGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldTokenURL, v))
}

// TokenURLLT applies the LT predicate on the "token_url" field.
func TokenURLLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldTokenURL, v))
}

// TokenURLLTE applies the LTE predicate on the "token_url" field.
func TokenURLLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldTokenURL, v))
}

// TokenURLContains applies the Contains predicate on the "token_url" field.
func TokenURLContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldTokenURL, v))
}

// TokenURLHasPrefix applies the HasPrefix predicate on the "token_url" field.
func TokenURLHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldTokenURL, v))
}

// TokenURLHasSuffix applies the HasSuffix predicate on the "token_url" field.
func TokenURLHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldTokenURL, v))
}

// TokenURLEqualFold applies the EqualFold predicate on the "token_url" field.
func TokenURLEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldTokenURL, v))
}

// TokenURLContainsFold applies the ContainsFold predicate on the "token_url" field.
func TokenURLContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldTokenURL, v))
}

// UserinfoURLEQ applies the EQ predicate on the "userinfo_url" field.
func UserinfoURLEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldUserinfoURL, v))
}

// UserinfoURLNEQ applies the NEQ predicate on the "userinfo_url" field.
func UserinfoURLNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldUserinfoURL, v))
}

// UserinfoURLIn applies the In predicate on the "userinfo_url" field.
func UserinfoURLIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldUserinfoURL, vs...))
}

// UserinfoURLNotIn applies the NotIn predicate on the "userinfo_url" field.
func UserinfoURLNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldUserinfoURL, vs...))
}

// UserinfoURLGT applies the GT predicate on the "userinfo_url" field.
func UserinfoURLGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldUserinfoURL, v))
}

// UserinfoURLGTE applies the GTE predicate on the "userinfo_url" field.
func UserinfoURLGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldUserinfoURL, v))
}

// UserinfoURLLT applies the LT predicate on the "userinfo_url" field.
func UserinfoURLLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldUserinfoURL, v))
}

// UserinfoURLLTE applies the LTE predicate on the "userinfo_url" field.
func UserinfoURLLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldUserinfoURL, v))
}

// UserinfoURLContains applies the Contains predicate on the "userinfo_url" field.
func UserinfoURLContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldUserinfoURL, v))
}

// UserinfoURLHasPrefix applies the HasPrefix predicate on the "userinfo_url" field.
func UserinfoURLHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldUserinfoURL, v))
}

// UserinfoURLHasSuffix applies the HasSuffix predicate on the "userinfo_url" field.
func UserinfoURLHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldUserinfoURL, v))
}

// UserinfoURLIsNil applies the IsNil predicate on the "userinfo_url" field.
func UserinfoURLIsNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIsNull(FieldUserinfoURL))
}

// UserinfoURLNotNil applies the NotNil predicate on the "userinfo_url" field.
func UserinfoURLNotNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotNull(FieldUserinfoURL))
}

// UserinfoURLEqualFold applies the EqualFold predicate on the "userinfo_url" field.
func UserinfoURLEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldUserinfoURL, v))
}

// UserinfoURLContainsFold applies the ContainsFold predicate on the "userinfo_url" field.
func UserinfoURLContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldUserinfoURL, v))
}

// LogoutURLEQ applies the EQ predicate on the "logout_url" field.
func LogoutURLEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldLogoutURL, v))
}

// LogoutURLNEQ applies the NEQ predicate on the "logout_url" field.
func LogoutURLNEQ(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldLogoutURL, v))
}

// LogoutURLIn applies the In predicate on the "logout_url" field.
func LogoutURLIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldLogoutURL, vs...))
}

// LogoutURLNotIn applies the NotIn predicate on the "logout_url" field.
func LogoutURLNotIn(vs ...string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldLogoutURL, vs...))
}

// LogoutURLGT applies the GT predicate on the "logout_url" field.
func LogoutURLGT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldLogoutURL, v))
}

// LogoutURLGTE applies the GTE predicate on the "logout_url" field.
func LogoutURLGTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldLogoutURL, v))
}

// LogoutURLLT applies the LT predicate on the "logout_url" field.
func LogoutURLLT(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldLogoutURL, v))
}

// LogoutURLLTE applies the LTE predicate on the "logout_url" field.
func LogoutURLLTE(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldLogoutURL, v))
}

// LogoutURLContains applies the Contains predicate on the "logout_url" field.
func LogoutURLContains(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContains(FieldLogoutURL, v))
}

// LogoutURLHasPrefix applies the HasPrefix predicate on the "logout_url" field.
func LogoutURLHasPrefix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasPrefix(FieldLogoutURL, v))
}

// LogoutURLHasSuffix applies the HasSuffix predicate on the "logout_url" field.
func LogoutURLHasSuffix(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldHasSuffix(FieldLogoutURL, v))
}

// LogoutURLIsNil applies the IsNil predicate on the "logout_url" field.
func LogoutURLIsNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIsNull(FieldLogoutURL))
}

// LogoutURLNotNil applies the NotNil predicate on the "logout_url" field.
func LogoutURLNotNil() predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotNull(FieldLogoutURL))
}

// LogoutURLEqualFold applies the EqualFold predicate on the "logout_url" field.
func LogoutURLEqualFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEqualFold(FieldLogoutURL, v))
}

// LogoutURLContainsFold applies the ContainsFold predicate on the "logout_url" field.
func LogoutURLContainsFold(v string) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldContainsFold(FieldLogoutURL, v))
}

// AuthStyleEQ applies the EQ predicate on the "auth_style" field.
func AuthStyleEQ(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldEQ(FieldAuthStyle, v))
}

// AuthStyleNEQ applies the NEQ predicate on the "auth_style" field.
func AuthStyleNEQ(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNEQ(FieldAuthStyle, v))
}

// AuthStyleIn applies the In predicate on the "auth_style" field.
func AuthStyleIn(vs ...uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldIn(FieldAuthStyle, vs...))
}

// AuthStyleNotIn applies the NotIn predicate on the "auth_style" field.
func AuthStyleNotIn(vs ...uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldNotIn(FieldAuthStyle, vs...))
}

// AuthStyleGT applies the GT predicate on the "auth_style" field.
func AuthStyleGT(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGT(FieldAuthStyle, v))
}

// AuthStyleGTE applies the GTE predicate on the "auth_style" field.
func AuthStyleGTE(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldGTE(FieldAuthStyle, v))
}

// AuthStyleLT applies the LT predicate on the "auth_style" field.
func AuthStyleLT(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLT(FieldAuthStyle, v))
}

// AuthStyleLTE applies the LTE predicate on the "auth_style" field.
func AuthStyleLTE(v uint8) predicate.OauthProvider {
	return predicate.OauthProvider(sql.FieldLTE(FieldAuthStyle, v))
}

// HasTokens applies the HasEdge predicate on the "tokens" edge.
func HasTokens() predicate.OauthProvider {
	return predicate.OauthProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TokensTable, TokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokensWith applies the HasEdge predicate on the "tokens" edge with a given conditions (other predicates).
func HasTokensWith(preds ...predicate.Token) predicate.OauthProvider {
	return predicate.OauthProvider(func(s *sql.Selector) {
		step := newTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OauthProvider) predicate.OauthProvider {
	return predicate.OauthProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OauthProvider) predicate.OauthProvider {
	return predicate.OauthProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OauthProvider) predicate.OauthProvider {
	return predicate.OauthProvider(sql.NotPredicates(p))
}
