// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: core.proto

package positionservice

import (
	"context"

	"github.com/wenpiner/last-admin-core/rpc/types/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApiInfo                            = core.ApiInfo
	ApiListRequest                     = core.ApiListRequest
	ApiListResponse                    = core.ApiListResponse
	BackupCodesResponse                = core.BackupCodesResponse
	BasePageRequest                    = core.BasePageRequest
	BasePageResp                       = core.BasePageResp
	BaseResponse                       = core.BaseResponse
	CleanExpiredTokensRequest          = core.CleanExpiredTokensRequest
	CleanExpiredTokensResponse         = core.CleanExpiredTokensResponse
	ConfigurationInfo                  = core.ConfigurationInfo
	ConfigurationListRequest           = core.ConfigurationListRequest
	ConfigurationListResponse          = core.ConfigurationListResponse
	CreateTokenRequest                 = core.CreateTokenRequest
	DepartmentInfo                     = core.DepartmentInfo
	DepartmentListRequest              = core.DepartmentListRequest
	DepartmentListResponse             = core.DepartmentListResponse
	DictInfo                           = core.DictInfo
	DictItemInfo                       = core.DictItemInfo
	DictItemListRequest                = core.DictItemListRequest
	DictItemListResponse               = core.DictItemListResponse
	DictListRequest                    = core.DictListRequest
	DictListResponse                   = core.DictListResponse
	DisableTotpRequest                 = core.DisableTotpRequest
	EmptyRequest                       = core.EmptyRequest
	EnableTotpRequest                  = core.EnableTotpRequest
	ID32Request                        = core.ID32Request
	ID32SRequest                       = core.ID32SRequest
	IDRequest                          = core.IDRequest
	IDSRequest                         = core.IDSRequest
	MenuInfo                           = core.MenuInfo
	MenuListRequest                    = core.MenuListRequest
	MenuListResponse                   = core.MenuListResponse
	MenuMeta                           = core.MenuMeta
	OauthCallbackRequest               = core.OauthCallbackRequest
	OauthLoginRequest                  = core.OauthLoginRequest
	OauthProviderInfo                  = core.OauthProviderInfo
	OauthProviderListRequest           = core.OauthProviderListRequest
	OauthProviderListResponse          = core.OauthProviderListResponse
	OauthRedirectResponse              = core.OauthRedirectResponse
	PositionInfo                       = core.PositionInfo
	PositionListRequest                = core.PositionListRequest
	PositionListResponse               = core.PositionListResponse
	RoleApiListResponse                = core.RoleApiListResponse
	RoleApiRequest                     = core.RoleApiRequest
	RoleConfigurationGroupListResponse = core.RoleConfigurationGroupListResponse
	RoleConfigurationGroupRequest      = core.RoleConfigurationGroupRequest
	RoleInfo                           = core.RoleInfo
	RoleListRequest                    = core.RoleListRequest
	RoleListResponse                   = core.RoleListResponse
	RoleMenuListResponse               = core.RoleMenuListResponse
	RoleMenuRequest                    = core.RoleMenuRequest
	StringListResponse                 = core.StringListResponse
	StringRequest                      = core.StringRequest
	TokenInfo                          = core.TokenInfo
	TokenListRequest                   = core.TokenListRequest
	TokenListResponse                  = core.TokenListResponse
	TotpInfo                           = core.TotpInfo
	TotpSetupConfirmResponse           = core.TotpSetupConfirmResponse
	TotpSetupResponse                  = core.TotpSetupResponse
	TotpStatusResponse                 = core.TotpStatusResponse
	UUIDRequest                        = core.UUIDRequest
	UUIDSRequest                       = core.UUIDSRequest
	UpdateTokenLastUsedRequest         = core.UpdateTokenLastUsedRequest
	UseBackupCodeRequest               = core.UseBackupCodeRequest
	UserInfo                           = core.UserInfo
	UserListRequest                    = core.UserListRequest
	UserListResponse                   = core.UserListResponse
	ValidateConfigurationRequest       = core.ValidateConfigurationRequest
	ValidateConfigurationResponse      = core.ValidateConfigurationResponse
	VerifyTotpCodeRequest              = core.VerifyTotpCodeRequest
	VerifyTotpCodeResponse             = core.VerifyTotpCodeResponse
	VerifyTotpSetupRequest             = core.VerifyTotpSetupRequest

	PositionService interface {
		// 创建或更新岗位
		CreateOrUpdatePosition(ctx context.Context, in *PositionInfo, opts ...grpc.CallOption) (*PositionInfo, error)
		// 删除岗位
		DeletePosition(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*BaseResponse, error)
		// 获取岗位
		GetPosition(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*PositionInfo, error)
		// 获取岗位列表
		ListPosition(ctx context.Context, in *PositionListRequest, opts ...grpc.CallOption) (*PositionListResponse, error)
	}

	defaultPositionService struct {
		cli zrpc.Client
	}
)

func NewPositionService(cli zrpc.Client) PositionService {
	return &defaultPositionService{
		cli: cli,
	}
}

// 创建或更新岗位
func (m *defaultPositionService) CreateOrUpdatePosition(ctx context.Context, in *PositionInfo, opts ...grpc.CallOption) (*PositionInfo, error) {
	client := core.NewPositionServiceClient(m.cli.Conn())
	return client.CreateOrUpdatePosition(ctx, in, opts...)
}

// 删除岗位
func (m *defaultPositionService) DeletePosition(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := core.NewPositionServiceClient(m.cli.Conn())
	return client.DeletePosition(ctx, in, opts...)
}

// 获取岗位
func (m *defaultPositionService) GetPosition(ctx context.Context, in *ID32Request, opts ...grpc.CallOption) (*PositionInfo, error) {
	client := core.NewPositionServiceClient(m.cli.Conn())
	return client.GetPosition(ctx, in, opts...)
}

// 获取岗位列表
func (m *defaultPositionService) ListPosition(ctx context.Context, in *PositionListRequest, opts ...grpc.CallOption) (*PositionListResponse, error) {
	client := core.NewPositionServiceClient(m.cli.Conn())
	return client.ListPosition(ctx, in, opts...)
}
